## The following values are all the default resource options for all the       
## containers running in pods that get deployed as a part of Zenko. We usually
## recommend not to specify default `resources` and to leave this as a conscious
## choice for the user. This also increases chances charts run on environments
## with little resources, such as Minikube. If you do want to specify resources,
## uncomment the `resources` lines, adjust them as necessary, and remove the
## curly braces after `resources:`. While all the options listed are default
## values, this file can be changed and applied at chart installation time by
## specifying `-f resources.yaml`.

backbeat:
  api:
    ## Resource requests and limits
    ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 100m
    #   memory: 256Mi

  ingestion:
    consumer:
      resources: {}
    producer:
      resources: {}

  lifecycle:
    conductor:
      resources: {}
    objectProcessor:
      resources: {}
    bucketProcessor:
      resources: {}

  replication:
    dataProcessor:
      resources: {}
    populator:
      resources: {}
    statusProcessor:
      resources: {}

  garbageCollector:
    consumer:
      resources: {}
 
cloudserver:
  resources: {}

mongodb-replicaset:
  resources: {}

  metrics:
    resources: {}

prometheus:
 server:
   resources: {}

 configmapReload:
   resources: {}

redis-ha:
  redis:
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
  sentinel:
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 200Mi

s3-data:
  resources: {}

zenko-nfs:
  resources: {}

zenko-queue:
  resources: {}
  kafkaHeapOptions: "-Xmx1G -Xms1G"

  ## Prometheus JMX Exporter: exposes the majority of Kafkas metrics
  prometheus:
    resources: {}

  ## Prometheus Kafka Exporter: exposes complimentary metrics to JMX Exporter
  kafka:
    resources: {}

zenko-quorum:
  resources: {}
  env:
    ZK_HEAP_SIZE: 2G

  exporters:
    jmx:
      resources: {}
    zookeeper:
      resources: {}

  jobs:
    chroots:
      resources: {}

