ingress:
  enabled: true
  servicePort: http
  tls: [  ]
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
  rules:
    - host: 'keycloak.zenko.local'
      paths:
        - path: /auth
          pathType: Prefix
