{{- if and .Values.shards .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
{{- $replicas := .Values.shards | int }}
{{- range $i, $e := until $replicas }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ printf "%s-shard%d-data" (include "common.names.fullname" $ ) $i }}
  {{- if $.Values.metrics.podMonitor.namespace }}
  namespace: {{ $.Values.metrics.podMonitor.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: shardsvr
    {{- if $.Values.metrics.podMonitor.additionalLabels }}
    {{- include "common.tplvalues.render" (dict "value" $.Values.metrics.podMonitor.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      {{- if $.Values.metrics.podMonitor.interval }}
      interval: {{ $.Values.metrics.podMonitor.interval }}
      {{- end }}
      {{- if $.Values.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: shardsvr
{{- end }}
{{- end }}
