apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cosmoses.zenko.io
spec:
  group: zenko.io
  names:
    kind: Cosmos
    listKind: CosmosList
    plural: cosmoses
    singular: cosmos
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
