{
 "title": "Kafka Metrics",
 "description": "Kafka metrics",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate{namespace=\"${namespace}\", job=\"${job}\"}, pod)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_cluster_partition_replicascount{namespace=\"${namespace}\", job=\"${job}\"}, topic)"
   },
   {
    "name": "online_broker",
    "query": "query_result(count(up{namespace=\"${namespace}\", job=\"${job}\"}))"
   }
  ]
 },
 "panels": [
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=\"${namespace}\", job=\"${job}\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"${namespace}\", job=\"${job}\",topic=\"\"}[1m]))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{namespace=\"${namespace}\", job=\"${job}\"}"
    },
    {
     "expr": "count(kafka_cluster_partition_replicascount{namespace=\"${namespace}\", job=\"${job}\"} <= 1)by(pod)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"${namespace}\", job=\"${job}\",topic=\"\"}[$__range]))",
     "legendFormat": "Total messages from ${__from:date:MM-DD hA} to ${__to:date:MM-DD hA}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kafka_network_socketserver_networkprocessoravgidle_percent{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}*100)",
     "legendFormat": "Network processor avg {{pod}}"
    }
   ]
  },
  { "title": "Request Handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "gauge",
   "description": "If <= 0 is very idle",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]) / 10000000",
     "legendFormat": "Request handler avg {{pod}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"Produce\",namespace=\"${namespace}\", job=\"${job}\",quantile=\"0.99\",pod=\"${broker}\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",namespace=\"${namespace}\", job=\"${job}\",quantile=\"0.99\",pod=\"${broker}\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",namespace=\"${namespace}\", job=\"${job}\",quantile=\"0.99\",pod=\"${broker}\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "title": "Produce Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"Produce\",namespace=\"${namespace}\", job=\"${job}\",quantile=\"0.99\",pod=\"${broker}\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",namespace=\"${namespace}\", job=\"${job}\",quantile=\"0.99\",pod=\"${broker}\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FetchFollow Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",namespace=\"${namespace}\", job=\"${job}\",quantile=\"0.99\",pod=\"${broker}\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps", "label": "Message/s" }
   ],
   "targets": [
    {
     "expr": "sort(sum(rate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"${namespace}\", job=\"${job}\",topic!=\"\",pod=\"${broker}\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"Produce\",namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))by(pod)",
     "legendFormat": "Request: {{pod}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "Bps", "label": "In (-) / Out (+)" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\",topic!=\"\"}[1m]))by(pod)",
     "legendFormat": "Bytes Out [{{pod}}]"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\",topic!=\"\"}[1m]))by(pod)",
     "legendFormat": "Bytes In [{{pod}}]"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Failed Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Produce Request Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{namespace=\"${namespace}\", job=\"${job}\",topic!=\"\",pod=\"${broker}\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"${namespace}\", job=\"${job}\",topic!=\"\",pod=\"${broker}\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))by(pod)",
     "legendFormat": "Broker - {{pod}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperexpires_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))by(pod)",
     "legendFormat": "Broker - {{pod}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"})by(pod)",
     "legendFormat": "Broker: {{pod}}"
    }
   ]
  },
  {
   "title": "Isr Shrinks / Isr Expands Per Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ops", "label": "Expands (-) / Shrinks (+)" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_replicamanager_isrshrinks_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))",
     "legendFormat": "ISR Shrinks Per Sec"
    },
    {
     "expr": "sum (irate(kafka_server_replicamanager_isrexpands_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))",
     "legendFormat": "ISR Expands Per Sec"
    }
   ]
  },
  {
   "title": "FetchFollower Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"FetchFollower\",namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))by(pod)",
     "legendFormat": "Request: {{pod}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{request=\"FetchConsumer\",namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[5m]))by(pod)",
     "legendFormat": "Request: {{pod}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Fetch Purgatory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{namespace=\"${namespace}\", job=\"${job}\",delayedOperation=\"Fetch\",pod=\"${broker}\"})by(pod)",
     "legendFormat": "Broker {{pod}}"
    }
   ]
  },
  {
   "title": "Total Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "reqps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\",topic!=\"\"}[1m]))by(pod)",
     "legendFormat": "Broker: {{pod}}"
    }
   ]
  },
  {
   "title": "Log Flush Stats Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_log_logflushstats_logflushrateandtimems_count{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[5m]))by(pod)",
     "legendFormat": "Broker - {{pod}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Producer Purgatory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{namespace=\"${namespace}\", job=\"${job}\",delayedOperation=\"Produce\",pod=\"${broker}\"})by(pod)",
     "legendFormat": "Broker {{pod}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_controller_controllerstats_leaderelectionrateandtimems_count{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))by(pod)",
     "legendFormat": "Broker - {{pod}}"
    }
   ]
  },
  {
   "title": "Partitions Leader Per Broker",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{namespace=\"${namespace}\", job=\"${job}\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Disk Usage Segment Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_log_log_size{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"})by(pod))",
     "legendFormat": "Instance Broker:  {{pod}}"
    }
   ]
  },
  {
   "title": "Count Partition per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_server_replicamanager_partitioncount{namespace=\"${namespace}\", job=\"${job}\"}) by(pod))",
     "legendFormat": "Instance Broker: {{pod}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threads Current",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 156 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 156 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"} )",
       "legendFormat": "Broker - {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 165 },
     "yaxes": [
      { "format": "s", "label": "Usage/s" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[5m])",
       "legendFormat": "Broker - {{pod}}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 165 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{namespace=\"${namespace}\", job=\"${job}\",pod=\"${broker}\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}