---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts: &docker_login
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /home/eve/.docker/config.json
- role: worker
  extraMounts: *docker_login
- role: worker
  extraMounts: *docker_login
- role: worker
  extraMounts: *docker_login
