{
 "title": "Kafka",
 "description": "Kafka Dashboard",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Cluster",
    "query": "label_values(kafka_server_app_info_version{namespace=\"${namespace}\", job=~\"^${selector}$|^${job}$\"}, job)"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate{namespace=\"${namespace}\", job=\"$instance\"}, pod)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_cluster_partition_replicascount{namespace=\"${namespace}\", job=\"$instance\"}, topic)"
   },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": {
     "query": "query_result(kafka_consumergroup_group_lag{namespace=\"${namespace}\",cluster_name=\"$instance\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"${namespace}\", job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"${namespace}\", job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{namespace=\"${namespace}\", job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"${namespace}\", job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"${namespace}\", job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"${namespace}\", job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=\"${namespace}\", job=\"$instance\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"${namespace}\", job=\"$instance\",topic=\"\"}[$__rate_interval]))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{namespace=\"${namespace}\", job=\"$instance\"}"
    },
    {
     "expr": "count(kafka_cluster_partition_replicascount{namespace=\"${namespace}\", job=\"$instance\"} <= 1)by(pod)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"${namespace}\", job=\"$instance\",topic=\"\"}[$__range]))",
     "legendFormat": "Total messages from ${__from:date:MM-DD hA} to ${__to:date:MM-DD hA}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kafka_network_socketserver_networkprocessoravgidle_percent{namespace=\"${namespace}\", job=\"$instance\",pod=\"${broker}\"}*100)",
     "legendFormat": "Network processor avg {{pod}}"
    }
   ]
  },
  { "title": "Request Handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "gauge",
   "description": "If <= 0 is very idle",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count_total{namespace=\"${namespace}\", job=\"$instance\",pod=\"${broker}\"}[$__rate_interval]) / 10000000",
     "legendFormat": "Request handler avg {{pod}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"Produce\",namespace=\"${namespace}\", job=\"$instance\",quantile=\"0.99\",pod=~\"$broker\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",namespace=\"${namespace}\", job=\"$instance\",quantile=\"0.99\",pod=~\"$broker\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",namespace=\"${namespace}\", job=\"$instance\",quantile=\"0.99\",pod=~\"$broker\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "title": "Produce Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"Produce\",namespace=\"${namespace}\", job=\"$instance\",quantile=\"0.99\",pod=~\"$broker\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",namespace=\"${namespace}\", job=\"$instance\",quantile=\"0.99\",pod=~\"$broker\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FetchFollow Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",namespace=\"${namespace}\", job=\"$instance\",quantile=\"0.99\",pod=~\"$broker\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps", "label": "Message/s" }
   ],
   "targets": [
    {
     "expr": "sort(sum(rate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[$__rate_interval]))by(topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"${namespace}\", job=\"$instance\",topic!=\"\",pod=~\"$broker\",topic=~\"$topic\"}[$__rate_interval]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[$__rate_interval]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[$__rate_interval]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"Produce\",namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "Bps", "label": "In (-) / Out (+)" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\",topic!=\"\"}[$__rate_interval]))by(pod)",
     "legendFormat": "Bytes Out [{{pod}}]"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\",topic!=\"\"}[$__rate_interval]))by(pod)",
     "legendFormat": "Bytes In [{{pod}}]"
    }
   ]
  },
  { "title": "Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Max estimated lag in seconds",
   "type": "graph",
   "description": "Max lag in seconds (extrapolated) and messages for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "s", "label": "Estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag_seconds{namespace=\"${namespace}\",cluster_name=\"$instance\",group=~\"$consumer_group\",group!=\"\"}",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Max lag in messages",
   "type": "graph",
   "description": "Max lag in messages for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Lag in number of messages" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag{namespace=\"${namespace}\",cluster_name=\"$instance\",group=~\"$consumer_group\",group!=\"\"}",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "$consumer_group",
   "type": "graph",
   "description": "Shows time lag on the left Y axis and message/offset lag on the right Y axis for a single consumer group.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "repeat": "consumer_group",
   "yaxes": [
    { "format": "s", "label": "Estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag_seconds{namespace=\"${namespace}\",cluster_name=\"$instance\",group=~\"$consumer_group\",group!=\"\"}",
     "legendFormat": "Consumer group estimated lag in time"
    },
    {
     "expr": "kafka_consumergroup_group_max_lag{namespace=\"${namespace}\",cluster_name=\"$instance\",group=~\"$consumer_group\",group!=\"\"}",
     "legendFormat": "Consumer group lag in offsets"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Under-replicated partitions by topic",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{namespace=\"${namespace}\",job=\"$instance\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Produce Request Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{namespace=\"${namespace}\",job=\"$instance\",pod=~\"$broker\",topic=~\"$topic\"}[$__rate_interval]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"${namespace}\",job=\"$instance\",pod=~\"$broker\",topic=~\"$topic\"}[$__rate_interval]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperexpires_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Isr Shrinks / Isr Expands Per Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "ops", "label": "Expands (-) / Shrinks (+)" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_replicamanager_isrshrinks_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))",
     "legendFormat": "ISR Shrinks Per Sec"
    },
    {
     "expr": "sum (irate(kafka_server_replicamanager_isrexpands_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))",
     "legendFormat": "ISR Expands Per Sec"
    }
   ]
  },
  {
   "title": "FetchFollower Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"FetchFollower\",namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "Request: {{pod}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{request=\"FetchConsumer\",namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Fetch Purgatory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{namespace=\"${namespace}\", job=\"$instance\",delayedOperation=\"Fetch\",pod=~\"$broker\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "reqps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\",topic!=\"\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Log Flush Stats Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_log_logflushstats_logflushrateandtimems_count_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Producer Purgatory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{namespace=\"${namespace}\", job=\"$instance\",delayedOperation=\"Produce\",pod=~\"$broker\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_controller_controllerstats_leaderelectionrateandtimems_count_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Partitions Leader Per Broker",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{namespace=\"${namespace}\", job=\"$instance\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Disk Usage Segment Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_log_log_size{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"})by(pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Count Partition per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_server_replicamanager_partitioncount{namespace=\"${namespace}\", job=\"$instance\"}) by(pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threads Current",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 175 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 175 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_used_bytes{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"} )",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 184 },
     "yaxes": [
      { "format": "s", "label": "Usage/s" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 184 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{namespace=\"${namespace}\", job=\"$instance\",pod=~\"$broker\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}