apiVersion: v1
kind: Service
metadata:
  name: azure-mock
spec:
  selector:
    name: azure-mock
  type: ClusterIP
  ports:
    - name: blob
      port: 80
      targetPort: blob
    - name: queue
      port: 81
      targetPort: queue
---
apiVersion: v1
kind: Pod
metadata:
  name: azure-mock-pod
  labels:
    name: azure-mock
    component: mock
spec:
  hostname: devstoreaccount1
  subdomain: azure-mock
  containers:
  - image: mcr.microsoft.com/azure-storage/azurite:3.21.0
    command: ["azurite", "-l", "/data", "--blobHost", "0.0.0.0", "--blobPort", "80", "--queueHost", "0.0.0.0","--queuePort", "81"]
    name: azurite
    ports:
      - name: blob
        containerPort: 80
      - name: queue
        containerPort: 81
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: azure-mock
spec:
  rules:
  - host: '*.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: blob
        path: /
        pathType: Prefix
  - host: 'azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: blob
        path: /
        pathType: Prefix
  - host: '*.blob.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: blob
        path: /
        pathType: Prefix
  - host: 'blob.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: blob
        path: /
        pathType: Prefix
  - host: 'queue.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: queue
        path: /
        pathType: Prefix
  - host: '*.queue.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: queue
        path: /
        pathType: Prefix
