---
apiVersion: zenko.io/v1alpha1
kind: ZenkoVersion
metadata:
  name: ${VERSION_FULL}
spec:
  imagePullPolicy: Always
  versions:
    management:
      ui:
        image: zenko-ui
        tag: 0.1.0
      api:
        image: pensieve-api
        tag: 611b9ca
      pushAPI:
        image: pensieve-api
        tag: 611b9ca
    cloudserver:
      image: cloudserver
      tag: 8.2.8
    backbeat:
      image: backbeat
      tag: 8.2.5
    blobserver:
      image: blobserver
      tag: 1.0.8
    jabba:
      image: jabba
      tag: 940d
    utapi:
      image: utapi
      tag: zenko-1.0.0
    secureChannelProxy:
      image: cloudserver
      tag: '8.2.8'
    localData:
      image: cloudserver
      tag: '8.2.8'
    metrics:
      image: cloudserver
      tag: '8.2.8'
    s3utils:
      image: s3utils
      tag: '1.8.2'
    zookeeper:
      image: zookeeper
      tag: 0.2.4
    kafka:
      cluster:
        image: kafka
        tag: 2.12-2.3.0
      cruiseControl:
        image: kafka-cruise-control
        tag: 2.0.0-alpha.3
      monitoring:
        image: jmx-javaagent
        tag: '0.12.0'
    vault:
      image: vault
      tag: 8.2.0-alpha.1
    shell:
      image: busybox
      tag: latest
    mongodb: '4.0-v1'
    redis:
      db:
        image: redis
        tag: 5.0.3
      exporter:
        image: redis_exporter
        tag: v1.8.0
      kubedb: '5.0.3-v1'
