{{- if .Values.ingress.enabled -}}
{{- $serviceName := printf "%s-%s" .Release.Name "cloudserver" | trunc 63 | trimSuffix "-" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "zenko.fullname" . }}
  labels:
    app: {{ template "zenko.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if or .Values.ingress.max_body_size .Values.ingress.annotations }}
  annotations:
{{- if .Values.ingress.max_body_size }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.max_body_size | quote }}
{{- end }}
{{- if .Values.ingress.annotations }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: http
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
