{{- if not .Values.global.orbit.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-service-secrets
  labels:
    app: {{ template "zenko.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials.json: "{{ printf "{\"Lifecycle\": {\"access\": \"%s\", \"secret\": \"%s\" }, \"Replication\": {\"access\": \"%s\", \"secret\": \"%s\" } }" (randAlphaNum 20 | upper) (randAlphaNum 40) (randAlphaNum 20 | upper) (randAlphaNum 40) | b64enc }}"
{{- end -}}
