{{- if and .Values.maintenance.debug.enabled (and .Values.maintenance.debug.accessKey .Values.maintenance.debug.secretKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zenko.debug" . }}
  labels:
{{ include "zenko.labels.standard" . | indent 4 }}
type: Opaque
data:
  accesskey: {{ .Values.maintenance.debug.accessKey | b64enc }}
  secretkey: {{ .Values.maintenance.debug.secretKey | b64enc }}
{{- end -}}
