---
varReference:
- path: metadata/name
  kind: ZenkoVersion
- path: spec/versions/management/ui/tag
  kind: ZenkoVersion
- path: spec/versions/management/api/tag
  kind: ZenkoVersion
- path: spec/versions/management/pushAPI/tag
  kind: ZenkoVersion
- path: spec/versions/cloudserver/tag
  kind: ZenkoVersion
- path: spec/versions/backbeat/tag
  kind: ZenkoVersion
- path: spec/versions/blobserver/tag
  kind: ZenkoVersion
- path: spec/versions/jabba/tag
  kind: ZenkoVersion
- path: spec/versions/utapi/tag
  kind: ZenkoVersion
- path: spec/versions/secureChannelProxy/tag
  kind: ZenkoVersion
- path: spec/versions/localData/tag
  kind: ZenkoVersion
- path: spec/versions/metrics/tag
  kind: ZenkoVersion
- path: spec/versions/s3utils/tag
  kind: ZenkoVersion
- path: spec/versions/zookeeper/tag
  kind: ZenkoVersion
- path: spec/versions/kafka/cluster/tag
  kind: ZenkoVersion
- path: spec/versions/kafka/cruiseControl/tag
  kind: ZenkoVersion
- path: spec/versions/kafka/monitoring/tag
  kind: ZenkoVersion
- path: spec/versions/vault/tag
  kind: ZenkoVersion
- path: spec/versions/shell/tag
  kind: ZenkoVersion
- path: spec/versions/mongodb
  kind: ZenkoVersion
- path: spec/versions/redis/db/tag
  kind: ZenkoVersion
- path: spec/versions/redis/exporter/tag
  kind: ZenkoVersion
- path: spec/versions/redis/kubedb
  kind: ZenkoVersion
