---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- zenkoversion.yaml

configurations:
- kustomizeconfig.yaml

configMapGenerator:
- name: zenko-version
  envs:
  - VERSION
  options:
    disableNameSuffixHash: true

vars:
- name: "VERSION"
  objref:
    kind: ConfigMap
    name: zenko-version
    apiVersion: v1
  fieldref:
    fieldpath: data.VERSION
- name: "VERSION_SUFFIX"
  objref:
    kind: ConfigMap
    name: zenko-version
    apiVersion: v1
  fieldref:
    fieldpath: data.VERSION_SUFFIX
