{{- if and .Values.pushgateway.enabled .Values.pushgateway.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := include "prometheus.pushgateway.fullname" . }}
{{- $servicePort := .Values.pushgateway.service.servicePort -}}
{{- $supportsIngressServiceObject := or (.Capabilities.APIVersions.Has "networking.k8s.io/v1") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1") -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
{{- if .Values.pushgateway.ingress.annotations }}
  annotations:
{{ toYaml .Values.pushgateway.ingress.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.pushgateway.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.pushgateway.fullname" . }}
spec:
  rules:
  {{- range .Values.pushgateway.ingress.hosts }}
  {{- $url := splitList "/" . }}
  {{ if $supportsIngressServiceObject -}}
  {{- include "prometheus.ingress.host_entry_with_service_obj" (dict "url" $url "service" $serviceName "port" $servicePort) | indent 4 }}
  {{- else -}}
  {{- include "prometheus.ingress.host_entry" (dict "url" $url "service" $serviceName "port" $servicePort) | indent 4 }}
  {{- end }}
  {{- end -}}
{{- if .Values.pushgateway.ingress.tls }}
  tls:
{{ toYaml .Values.pushgateway.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
