---
name: "Setup End2End environment"
description: "installation of dependencies"

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |-
          set -exu;
          sudo dnf install -y \
            ca-certificates \
            curl \
            dnf-plugins-core \
            expect \
            gcc \
            gcc-c++ \
            git \
            git-lfs \
            jq \
            libselinux-python3 \
            m4 \
            make \
            openssl \
            pigz \
            python2 \
            python2-virtualenv \
            python3 \
            python3-pip \
            rsync \
            tar \
            virtualenv \
            wget

          sudo curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${{ env.KIND_VERSION }}/kind-linux-amd64
          sudo chmod +x ./kind
          sudo mv kind /usr/bin/
          sudo kind -h
          kind -h
          sudo curl -sSL https://get.helm.sh/helm-${{ env.HELM_VERSION }}-linux-amd64.tar.gz | sudo tar -xvz
          sudo install linux-amd64/helm /usr/local/bin
          sudo rm -rf linux-amd64
          sudo wget https://github.com/mikefarah/yq/releases/download/${{ env.YQ_VERSION }}/${{ env.YQ_BINARY }} -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          sudo curl -sSL https://github.com/tilt-dev/tilt/releases/download/v${{ env.TILT_VERSION }}/tilt.${{ env.TILT_VERSION }}.linux.x86_64.tar.gz | sudo tar xzvf -
          sudo mv tilt /usr/local/bin
          sudo chmod +x /usr/local/bin/tilt
          sudo curl -sSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${{ env.KUSTOMIZE_VERSION }}/kustomize_${{ env.KUSTOMIZE_VERSION }}_linux_amd64.tar.gz | sudo tar -xvz
          sudo install kustomize /usr/local/bin
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3
      with:
        version: 'v${{ env.KUBECTL_VERSION }}'
