{
 "title": "Backbeat",
 "tags": [ "backbeat" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "CRR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sites",
   "type": "graph",
   "description": "CRR number of sites",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crr_number_of_sites{app=\"backbeat-api\"}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "description": "CRR number of objects replicated (operations)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crr_number_of_operations{app=\"backbeat-api\"}"
    }
   ]
  },
  {
   "title": "Operations completed",
   "type": "graph",
   "description": "CRR number of operations completed",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crr_number_of_operations_completed{app=\"backbeat-api\"}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "description": "CRR number of bytes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crr_number_of_bytes{app=\"backbeat-api\"}"
    }
   ]
  },
  {
   "title": "Bytes completed",
   "type": "graph",
   "description": "CRR number of bytes completed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "crr_number_of_bytes_completed" }
   ]
  }
 ]
}