apiVersion: v1
kind: Service
metadata:
  name: {{ template "ceph.fullname" . }}
  labels:
    app: {{ template "ceph.name" . }}
    chart: {{ template "ceph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ceph.service.type }}
  ports:
    - port: {{ .Values.ceph.service.externalPort }}
      targetPort: {{ .Values.ceph.service.internalPort }}
      protocol: TCP
      name: {{ .Values.ceph.service.name }}
  selector:
    app: {{ template "ceph.name" . }}
    release: {{ .Release.Name }}
