CREATE DATABASE IF NOT EXISTS logs;

CREATE TABLE IF NOT EXISTS logs.access_logs
(
    insertedAt             DateTime DEFAULT now(),
    hostname               LowCardinality(Nullable(String)),
    startTime              Nullable(DateTime64(3)),
    requester              Nullable(String),
    operation              Nullable(String),
    requestURI             Nullable(String),
    errorCode              Nullable(String),
    objectSize             Nullable(UInt64),
    totalTime              Nullable(Float32),
    turnAroundTime         Nullable(Float32),
    referer                Nullable(String),
    userAgent              Nullable(String),
    versionId              Nullable(String),
    signatureVersion       LowCardinality(Nullable(String)),
    cipherSuite            LowCardinality(Nullable(String)),
    authenticationType     LowCardinality(Nullable(String)),
    hostHeader             Nullable(String),
    tlsVersion             LowCardinality(Nullable(String)),
    aclRequired            LowCardinality(Nullable(String)),
    bucketOwner            Nullable(String),
    bucketName             String DEFAULT '',
    req_id                 String DEFAULT '',
    bytesSent              Nullable(UInt64),
    clientIP               Nullable(String),
    httpCode               Nullable(UInt16),
    objectKey              Nullable(String),
    logFormatVersion       LowCardinality(Nullable(String)),
    loggingEnabled         Bool DEFAULT false,
    loggingTargetBucket    String DEFAULT '',
    loggingTargetPrefix    String DEFAULT '',
    awsAccessKeyID         Nullable(String),
    raftSessionID          UInt16 DEFAULT 0
)
Engine = MergeTree()
PARTITION BY toStartOfInterval(insertedAt, INTERVAL 1 HOUR)
ORDER BY (raftSessionID, bucketName, insertedAt, assumeNotNull(startTime), req_id);

CREATE TABLE IF NOT EXISTS logs.access_logs_ingest
(
    timestamp              DateTime DEFAULT now(),
    insertedAt             DateTime DEFAULT now(),
    hostname               LowCardinality(Nullable(String)),
    action                 LowCardinality(Nullable(String)),
    accountName            Nullable(String),
    userName               Nullable(String),
    httpMethod             LowCardinality(Nullable(String)),
    bytesDeleted           Nullable(UInt64),
    bytesReceived          Nullable(UInt64),
    bodyLength             Nullable(UInt64),
    contentLength          Nullable(UInt64),
    elapsed_ms             Nullable(Float32),
    rateLimited            Nullable(Bool),
    rateLimitSource        LowCardinality(Nullable(String)),
    startTime              Nullable(DateTime64(3)),
    requester              Nullable(String),
    operation              Nullable(String),
    requestURI             Nullable(String),
    errorCode              Nullable(String),
    objectSize             Nullable(UInt64),
    totalTime              Nullable(Float32),
    turnAroundTime         Nullable(Float32),
    referer                Nullable(String),
    userAgent              Nullable(String),
    versionId              Nullable(String),
    signatureVersion       LowCardinality(Nullable(String)),
    cipherSuite            LowCardinality(Nullable(String)),
    authenticationType     LowCardinality(Nullable(String)),
    hostHeader             Nullable(String),
    tlsVersion             LowCardinality(Nullable(String)),
    aclRequired            LowCardinality(Nullable(String)),
    bucketOwner            Nullable(String),
    bucketName             String DEFAULT '',
    req_id                 String DEFAULT '',
    bytesSent              Nullable(UInt64),
    clientIP               Nullable(String),
    httpCode               Nullable(UInt16),
    objectKey              Nullable(String),
    logFormatVersion       LowCardinality(Nullable(String)),
    loggingEnabled         Bool DEFAULT false,
    loggingTargetBucket    String DEFAULT '',
    loggingTargetPrefix    String DEFAULT '',
    awsAccessKeyID         Nullable(String),
    raftSessionID          UInt16 DEFAULT 0
)
Engine = Null();

CREATE MATERIALIZED VIEW IF NOT EXISTS logs.access_logs_ingest_mv
TO logs.access_logs
AS
SELECT
    insertedAt,
    hostname,
    startTime,
    requester,
    operation,
    requestURI,
    errorCode,
    objectSize,
    totalTime,
    turnAroundTime,
    referer,
    userAgent,
    versionId,
    signatureVersion,
    cipherSuite,
    authenticationType,
    hostHeader,
    tlsVersion,
    aclRequired,
    bucketOwner,
    bucketName,
    req_id,
    bytesSent,
    clientIP,
    httpCode,
    objectKey,
    logFormatVersion,
    loggingEnabled,
    loggingTargetBucket,
    loggingTargetPrefix,
    awsAccessKeyID,
    raftSessionID
FROM logs.access_logs_ingest
WHERE loggingEnabled = true;
