{
 "title": "Zenko DR ${zenkoName}",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "KafkaConnect Source",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${kafka_connect_src_job}\", namespace=\"${namespace}\", drSinkInstance=\"\"})",
     "query": "sum(up{job=\"${kafka_connect_src_job}\", namespace=\"${namespace}\", drSinkInstance=\"\"})"
    }
   ]
  },
  {
   "title": "KafkaConnect Sink",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${kafka_connect_sink_job}\", namespace=\"${namespace}\", drSinkInstance=\"${dr_sink_instance}\"})",
     "query": "sum(up{job=\"${kafka_connect_sink_job}\", namespace=\"${namespace}\", drSinkInstance=\"${dr_sink_instance}\"})"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${kafka_instance}\", namespace=\"${namespace}\"})",
     "query": "sum(up{job=\"${kafka_instance}\", namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Last lifecycle op",
   "type": "stat",
   "description": "Time since the last eligible op on the primary site.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - s3_lifecycle_last_timestamp_ms{location=~\"${locations}\", job=~\"${lifecycle_jobs}\", namespace=\"${namespace}\"}",
     "query": "time() - s3_lifecycle_last_timestamp_ms{location=~\"${locations}\", job=~\"${lifecycle_jobs}\", namespace=\"${namespace}\"}"
    }
   ]
  },
  {
   "title": "Last DR mongo write",
   "type": "stat",
   "description": "Time since the last mongo DB write on DR site.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - mongodb_ss_repl_lastWrite_lastWriteDate{job=~\"${mongo_jobs}\", namespace=\"${namespace}\", drSinkInstance=\"${dr_sink_instance}\"}",
     "query": "time() - mongodb_ss_repl_lastWrite_lastWriteDate{job=~\"${mongo_jobs}\", namespace=\"${namespace}\", drSinkInstance=\"${dr_sink_instance}\"}"
    }
   ]
  },
  { "title": "Kafka Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Kafka Connect Source Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{namespace=\"${namespace}\", drSinkInstance=\"\", job=\"${kafka_connect_src_job}\"})",
     "legendFormat": " ",
     "query": "sum(kafka_consumer_fetch_manager_records_lag{namespace=\"${namespace}\", drSinkInstance=\"\", job=\"${kafka_connect_src_job}\"})"
    }
   ]
  },
  {
   "title": "Kafka Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_max_lag{cluster_name=\"${kafka_instance}\", namespace=\"${namespace}\"})",
     "legendFormat": " ",
     "query": "max(kafka_consumergroup_group_max_lag{cluster_name=\"${kafka_instance}\", namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Kafka Connect Sink Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{namespace=\"${namespace}\", drSinkInstance=\"${dr_sink_instance}\", job=\"${kafka_connect_sink_job}\"})",
     "legendFormat": " ",
     "query": "sum(kafka_consumer_fetch_manager_records_lag{namespace=\"${namespace}\", drSinkInstance=\"${dr_sink_instance}\", job=\"${kafka_connect_sink_job}\"})"
    }
   ]
  },
  { "title": "Processing rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Lifecycle Archive Rate (source)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_lifecycle_duration_seconds_count{location=~\"${locations}\", job=~\"${lifecycle_jobs}\", namespace=\"${namespace}\", type=\"archive\"}[$__rate_interval]))",
     "legendFormat": " ",
     "query": "sum(rate(s3_lifecycle_duration_seconds_count{location=~\"${locations}\", job=~\"${lifecycle_jobs}\", namespace=\"${namespace}\", type=\"archive\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Kafka Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"${kafka_instance}\", namespace=\"${namespace}\", topic=\"\"}[$__rate_interval]))",
     "legendFormat": " ",
     "query": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"${kafka_instance}\", namespace=\"${namespace}\", topic=\"\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Metadata Write Rate (sink)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_connect_mongodb_sink_task_metrics_in_task_put{job=\"${kafka_connect_sink_job}\", namespace=\"${namespace}\"}[$__rate_interval]))",
     "legendFormat": " ",
     "query": "sum(rate(kafka_connect_mongodb_sink_task_metrics_in_task_put{job=\"${kafka_connect_sink_job}\", namespace=\"${namespace}\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}