{
 "title": "MongoDB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobs",
    "label": "MongoDB instance type",
    "query": "label_values(mongodb_up{namespace=\"${namespace}\", job=~\"${namespace}/${job}.*\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB services state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_up{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}) by (pod)",
     "query": "sum(mongodb_up{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": {
    "reduceOptions": {
     "calcs": [
      {
       "calcs": [ "lastNotNull" ],
       "fields": "/^mongodb$/",
       "values": false
      }
     ]
    }
   },
   "targets": [
    {
     "expr": "count by (mongodb) (mongodb_version_info{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}) > 0",
     "query": "count by (mongodb) (mongodb_version_info{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}) > 0",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Smallest oplog window",
   "type": "stat",
   "description": "This number represents the history window of the currently most used MongoDB shard. Losing a secondary for more than this duration will result in a divergence.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(mongodb_mongod_replset_oplog_head_timestamp{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"} - mongodb_mongod_replset_oplog_tail_timestamp{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "min(mongodb_mongod_replset_oplog_head_timestamp{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"} - mongodb_mongod_replset_oplog_tail_timestamp{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_indexSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum(mongodb_dbstats_indexSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "legendFormat": "Indexes"
    },
    {
     "expr": "sum(mongodb_dbstats_fsUsedSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"} - mongodb_dbstats_indexSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum(mongodb_dbstats_fsUsedSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"} - mongodb_dbstats_indexSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "legendFormat": "Documents"
    },
    {
     "expr": "sum(mongodb_dbstats_fsTotalSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"} - mongodb_dbstats_fsUsedSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum(mongodb_dbstats_fsTotalSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"} - mongodb_dbstats_fsUsedSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "stat",
   "description": "Total operations per second across selected jobs",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "sum(rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Active Cursors",
   "type": "stat",
   "description": "Total number of active cursors across selected jobs",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cursors" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_metrics_cursor_open{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "sum(mongodb_ss_metrics_cursor_open{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})"
    }
   ]
  },
  {
   "title": "Avg document size",
   "type": "stat",
   "description": "Average size of documents in the database",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_dbstats_avgObjSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "avg(mongodb_dbstats_avgObjSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "stat",
   "description": "Shows information about the disk space usage of the specified mountpoint.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_dbstats_fsUsedSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}) / avg(mongodb_dbstats_fsTotalSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "avg(mongodb_dbstats_fsUsedSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}) / avg(mongodb_dbstats_fsTotalSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})"
    }
   ]
  },
  {
   "title": "Size of Collections",
   "type": "stat",
   "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_storageSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\"})",
     "query": "sum(mongodb_dbstats_storageSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Number of Collections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_mongod_db_collections_total{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum(mongodb_mongod_db_collections_total{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg documents per shard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_objects{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}",
     "query": "mongodb_dbstats_objects{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}"
    }
   ]
  },
  {
   "title": "Number of indexes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_indexes{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum(mongodb_dbstats_indexes{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "legendFormat": "Metadata database"
    }
   ]
  },
  {
   "title": "Documents: configsvr",
   "type": "stat",
   "description": "Number of documents in config server (admin/config/local databases)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_objects{namespace=\"${namespace}\", database=~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum(mongodb_dbstats_objects{namespace=\"${namespace}\", database=~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})"
    }
   ]
  },
  {
   "title": "Index Size: configsvr",
   "type": "stat",
   "description": "Total index size for config server (admin/config/local databases)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_indexSize{namespace=\"${namespace}\", database=~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum(mongodb_dbstats_indexSize{namespace=\"${namespace}\", database=~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})"
    }
   ]
  },
  {
   "title": "Shard balancing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (job) (mongodb_mongos_sharding_chunks_is_balanced{namespace=\"${namespace}\"})",
     "query": "max by (job) (mongodb_mongos_sharding_chunks_is_balanced{namespace=\"${namespace}\"})",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Documents Distribution Across Shards",
   "type": "piechart",
   "description": "Distribution of user documents across all shards",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (mongodb_dbstats_objects{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum by (job) (mongodb_dbstats_objects{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Index Size Distribution Across Shards",
   "type": "piechart",
   "description": "Distribution of user index sizes across all shards",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (mongodb_dbstats_indexSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum by (job) (mongodb_dbstats_indexSize{namespace=\"${namespace}\", database!~\"admin|config|local\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})"
    }
   ]
  },
  {
   "title": "Shard Server States",
   "type": "state-timeline",
   "description": "ReplSet statuses during the selected time range.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by (pod) (mongodb_mongod_replset_my_state{namespace=\"${namespace}\", job=~\"${namespace}/${job}-shard.*-data\"})",
     "query": "max by (pod) (mongodb_mongod_replset_my_state{namespace=\"${namespace}\", job=~\"${namespace}/${job}-shard.*-data\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Shard configuration States",
   "type": "state-timeline",
   "description": "ReplSet statuses during the selected time range.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max by (pod) (mongodb_mongod_replset_my_state{namespace=\"${namespace}\", job=~\"${namespace}/${job}-configsvr\"})",
     "query": "max by (pod) (mongodb_mongod_replset_my_state{namespace=\"${namespace}\", job=~\"${namespace}/${job}-configsvr\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "MongoDB proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "MongoS cursors open against selected instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (job) (mongodb_ss_metrics_cursor_open{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "sum by (job) (mongodb_ss_metrics_cursor_open{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (mongodb_ss_connections{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", conn_type=\"current\"})",
     "query": "sum by(job) (mongodb_ss_connections{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", conn_type=\"current\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Active cursors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "cursors" } },
   "targets": [
    {
     "expr": "max(mongodb_ss_metrics_cursor_open{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "max(mongodb_ss_metrics_cursor_open{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "Open cursors"
    }
   ]
  },
  {
   "title": "Data operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", legacy_op_type=~\"query|getmore\"}[$__rate_interval]))",
     "query": "sum by (job) (rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", legacy_op_type=~\"query|getmore\"}[$__rate_interval]))",
     "legendFormat": "Read - {{ job }}"
    },
    {
     "expr": "sum by (job) (rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", legacy_op_type=~\"insert|update|delete\"}[$__rate_interval]))",
     "query": "sum by (job) (rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", legacy_op_type=~\"insert|update|delete\"}[$__rate_interval]))",
     "legendFormat": "Write - {{ job }}"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "timeseries",
   "description": "Replication operations per second by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (legacy_op_type) (rate(mongodb_ss_opcountersRepl{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval]))",
     "query": "sum by (legacy_op_type) (rate(mongodb_ss_opcountersRepl{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval]))",
     "legendFormat": "repl_{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Operations by command",
   "type": "timeseries",
   "description": "Ops classified by legacy wire protocol type (query, insert, update, delete, getmore). And (from the internal TTL threads) the docs deletes/sec by TTL indexes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_metrics_ttl_deletedDocuments{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval]))",
     "query": "sum(rate(mongodb_ss_metrics_ttl_deletedDocuments{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval]))",
     "legendFormat": "ttl_delete"
    },
    {
     "expr": "sum by (legacy_op_type) (rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval]))",
     "query": "sum by (legacy_op_type) (rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval]))",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Cursor created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "avg by (pod) (increase(mongodb_ss_metrics_cursor_totalOpened{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "avg by (pod) (increase(mongodb_ss_metrics_cursor_totalOpened{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "MongoDB Connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(mongodb_ss_connections{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", conn_type=\"current\"})",
     "query": "avg(mongodb_ss_connections{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", conn_type=\"current\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "avg(mongodb_ss_connections{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", conn_type=\"available\"})",
     "query": "avg(mongodb_ss_connections{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", conn_type=\"available\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(mongodb_ss_globalLock_activeClients_readers{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "avg(mongodb_ss_globalLock_activeClients_readers{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "Active readers clients"
    },
    {
     "expr": "avg(mongodb_ss_globalLock_activeClients_writers{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "avg(mongodb_ss_globalLock_activeClients_writers{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "Active writers clients"
    },
    {
     "expr": "avg(mongodb_ss_transactions_currentActive{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "avg(mongodb_ss_transactions_currentActive{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "Active transactions"
    },
    {
     "expr": "avg(mongodb_ss_transactions_currentInactive{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "avg(mongodb_ss_transactions_currentInactive{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "Inactive transactions"
    }
   ]
  },
  {
   "title": "Disk Reads Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{namespace=\"${namespace}\", pod=~\"${jobs}.*\"}[$__rate_interval]))",
     "query": "sum by(pod) (rate(container_fs_reads_total{namespace=\"${namespace}\", pod=~\"${jobs}.*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_total{namespace=\"${namespace}\", pod=~\"${jobs}.*\"}[$__rate_interval]))",
     "query": "sum by(pod) (rate(container_fs_writes_total{namespace=\"${namespace}\", pod=~\"${jobs}.*\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Oplog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Oplog Recovery Window",
   "type": "timeseries",
   "description": "Timespan window between newest and the oldest op in the Oplog collection.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_oplog_head_timestamp{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}-mongodb_mongod_replset_oplog_tail_timestamp{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}",
     "query": "mongodb_mongod_replset_oplog_head_timestamp{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}-mongodb_mongod_replset_oplog_tail_timestamp{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Average Operation Latency",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(mongodb_mongod_op_latencies_latency_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])) / sum by(type) (rate(mongodb_mongod_op_latencies_ops_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "sum by(type) (rate(mongodb_mongod_op_latencies_latency_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])) / sum by(type) (rate(mongodb_mongod_op_latencies_ops_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "Replication lag is the delay needed to replicate data from primary to secondary nodes. Should typically stay within a few seconds. If lag keeps increasing, it means secondary nodes cannot replicate data fast enough to keep up with the write rate to the primary.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "last_over_time(mongodb_mongod_replset_member_replication_lag{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]) > 0",
     "query": "last_over_time(mongodb_mongod_replset_member_replication_lag{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flow Control Count",
   "type": "timeseries",
   "description": "Number of times flow control was engaged to prevent the primary from being overwhelmed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(mongodb_ss_flowControl_isLaggedCount{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "max(rate(mongodb_ss_flowControl_isLaggedCount{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "legendFormat": "fc_count"
    }
   ]
  },
  {
   "title": "Flow Control Time",
   "type": "timeseries",
   "description": "Total time spent in flow control to manage write rate.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(rate(mongodb_ss_flowControl_isLaggedTimeMicros{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "max(rate(mongodb_ss_flowControl_isLaggedTimeMicros{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "legendFormat": "fc_time"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Query execution times",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (op_type) (rate(mongodb_ss_opLatencies_latency{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])) / sum by (op_type) (rate(mongodb_ss_opLatencies_ops{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "sum by (op_type) (rate(mongodb_ss_opLatencies_latency{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])) / sum by (op_type) (rate(mongodb_ss_opLatencies_ops{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "Queued Operations by Type",
   "type": "timeseries",
   "description": "Operations queued due to a lock, broken down by operation type (summed across all shards).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type) (mongodb_mongod_global_lock_current_queue{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "query": "sum by (type) (mongodb_mongod_global_lock_current_queue{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Queued Operations by pod",
   "type": "timeseries",
   "description": "Total reader and writer operations queued due to locks, aggregated by job/shard.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (mongodb_ss_globalLock_currentQueue{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", count_type=~\"readers|writers\"})",
     "query": "sum by(pod) (mongodb_ss_globalLock_currentQueue{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", count_type=~\"readers|writers\"})"
    }
   ]
  },
  {
   "title": "Write Conflicts per Second",
   "type": "timeseries",
   "description": "The ratio of write conflicts to the total number of write operations. A value of 0% means no write conflicts occurred, while a value of 100% means all write operations were conflicts.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_metrics_operation_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"writeConflicts\"}[$__rate_interval])) / sum(rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", legacy_op_type=~\"insert|update|delete\"}[$__rate_interval]))",
     "query": "sum(rate(mongodb_mongod_metrics_operation_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"writeConflicts\"}[$__rate_interval])) / sum(rate(mongodb_ss_opcounters{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", legacy_op_type=~\"insert|update|delete\"}[$__rate_interval]))",
     "legendFormat": "Write conflict ratio"
    }
   ]
  },
  {
   "title": "Reads & Writes clients locks",
   "type": "timeseries",
   "description": "Number of locks held by readers and writers",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(mongodb_ss_globalLock_activeClients_readers{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "avg(mongodb_ss_globalLock_activeClients_readers{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "Active Readers"
    },
    {
     "expr": "avg(mongodb_ss_globalLock_activeClients_writers{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "avg(mongodb_ss_globalLock_activeClients_writers{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "Active Writers"
    },
    {
     "expr": "avg(mongodb_ss_globalLock_currentQueue{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", count_type=\"readers\"})",
     "query": "avg(mongodb_ss_globalLock_currentQueue{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", count_type=\"readers\"})",
     "legendFormat": "Queued Readers"
    },
    {
     "expr": "avg(mongodb_ss_globalLock_currentQueue{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", count_type=\"writers\"})",
     "query": "avg(mongodb_ss_globalLock_currentQueue{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", count_type=\"writers\"})",
     "legendFormat": "Queued Writers"
    }
   ]
  },
  {
   "title": "WiredTiger Engine Cache hit/miss ratio",
   "type": "timeseries",
   "description": "The ratio of pages requested from the cache that were found in the cache (hit) vs. pages that were not found in the cache (miss). A value of 100% means all pages requested were found in the cache.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - rate(mongodb_ss_wt_cache_pages_read_into_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval]) / rate(mongodb_ss_wt_cache_pages_requested_from_the_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval])",
     "query": "1 - rate(mongodb_ss_wt_cache_pages_read_into_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval]) / rate(mongodb_ss_wt_cache_pages_requested_from_the_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Ratio of documents scanned per query",
   "type": "timeseries",
   "description": "Ratio of Documents (or Index entries) scanned / documents returned. A value of 1 means all documents returned exactly match query criteria for the sample period.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum(irate(mongodb_mongod_metrics_query_executor_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"scanned_objects\"}[$__rate_interval])) / sum(irate(mongodb_mongod_metrics_document_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"returned\"}[$__rate_interval]))",
     "query": "sum(irate(mongodb_mongod_metrics_query_executor_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"scanned_objects\"}[$__rate_interval])) / sum(irate(mongodb_mongod_metrics_document_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"returned\"}[$__rate_interval]))",
     "legendFormat": "Scanned objects / returned"
    },
    {
     "expr": "sum(irate(mongodb_mongod_metrics_query_executor_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"scanned\"}[$__rate_interval])) / sum(irate(mongodb_mongod_metrics_document_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"returned\"}[$__rate_interval]))",
     "query": "sum(irate(mongodb_mongod_metrics_query_executor_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"scanned\"}[$__rate_interval])) / sum(irate(mongodb_mongod_metrics_document_total{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", state=\"returned\"}[$__rate_interval]))",
     "legendFormat": "Scanned idx / returned"
    }
   ]
  },
  { "title": "Resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Stacked CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(mongodb_sys_cpu_user_ms{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]) / 1000)",
     "query": "sum by (job) (rate(mongodb_sys_cpu_user_ms{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]) / 1000)",
     "legendFormat": "User {{ job }}"
    },
    {
     "expr": "sum by (job) (rate(mongodb_sys_cpu_iowait_ms{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]) / 1000)",
     "query": "sum by (job) (rate(mongodb_sys_cpu_iowait_ms{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]) / 1000)",
     "legendFormat": "IO Wait {{ job }}"
    },
    {
     "expr": "sum by (job) (rate(mongodb_sys_cpu_system_ms{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]) / 1000)",
     "query": "sum by (job) (rate(mongodb_sys_cpu_system_ms{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]) / 1000)",
     "legendFormat": "System {{ job }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodb_ss_mem_resident{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}",
     "query": "mongodb_ss_mem_resident{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])",
     "query": "rate(mongodb_ss_network_bytesIn{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])",
     "legendFormat": "{{pod}}: In"
    },
    {
     "expr": "-rate(mongodb_ss_network_bytesOut{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])",
     "query": "-rate(mongodb_ss_network_bytesOut{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])",
     "legendFormat": "{{pod}}: Out"
    }
   ]
  },
  {
   "title": "Disk IO Utilization (all instances)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_blkio_device_usage_total{namespace=\"${namespace}\", pod=~\"${jobs}.*\", operation=\"Total\"}[$__rate_interval]))",
     "query": "sum by(pod) (rate(container_blkio_device_usage_total{namespace=\"${namespace}\", pod=~\"${jobs}.*\", operation=\"Total\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Wiredtiger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Eviction thread created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_wt_cache_eviction_worker_thread_created{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])",
     "query": "rate(mongodb_ss_wt_cache_eviction_worker_thread_created{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Eviction threads removed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_wt_cache_eviction_worker_thread_removed{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])",
     "query": "rate(mongodb_ss_wt_cache_eviction_worker_thread_removed{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of active eviction threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    {
     "expr": "mongodb_ss_wt_cache_eviction_worker_thread_active{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}",
     "query": "mongodb_ss_wt_cache_eviction_worker_thread_active{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Available Concurrency Tickets by Pod",
   "type": "timeseries",
   "description": "Number of available WT concurrency tickets by pod. Shows current ticket availability for read and write operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod, txn_rw) (mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "sum by (pod, txn_rw) (mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "{{txn_type}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Write Concurrency Tickets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", txn_rw=\"write\"})",
     "query": "sum by (pod) (mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", txn_rw=\"write\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read Concurrency Tickets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", txn_rw=\"read\"})",
     "query": "sum by (pod) (mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", txn_rw=\"read\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page Eviction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(mongodb_ss_wt_cache_eviction_worker_thread_evicting_pages{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "sum by (pod) (rate(mongodb_ss_wt_cache_eviction_worker_thread_evicting_pages{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_wt_cache_bytes_written_from_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "sum(rate(mongodb_ss_wt_cache_bytes_written_from_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "legendFormat": "written_from_cache"
    },
    {
     "expr": "sum(rate(mongodb_ss_wt_cache_bytes_read_into_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "query": "sum(rate(mongodb_ss_wt_cache_bytes_read_into_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"}[$__rate_interval]))",
     "legendFormat": "read_into_cache"
    }
   ]
  },
  {
   "title": "Evictions from application threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_wt_cache_modified_pages_evicted_by_application_threads{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval])",
     "query": "rate(mongodb_ss_wt_cache_modified_pages_evicted_by_application_threads{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\", rs_state=\"1\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_mongod_wiredtiger_cache_max_bytes{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "sum(mongodb_mongod_wiredtiger_cache_max_bytes{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(mongodb_mongod_wiredtiger_cache_bytes{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "sum(mongodb_mongod_wiredtiger_cache_bytes{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "query": "sum(mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache{namespace=\"${namespace}\", job=~\"${namespace}/${jobs}\"})",
     "legendFormat": "dirty"
    }
   ]
  }
 ]
}