---
name: "Docker check"
description: "check if docker daemon is running"

runs:
  using: composite
  steps:
    - name: Wait for Docker daemon to be ready
      shell: bash
      run: |-
          bash -c '
          for i in {1..150}
          do
            sudo docker info &> /dev/null && exit
            sleep 2
          done
          echo "Could not reach Docker daemon from buildbot worker" >&2
          exit 1'
