#!/usr/bin/with-contenv sh
set -e

PROXY_OPTS=" --confdir /config \
            --proxyauth ${PROXY_USER:-scality}:${PROXY_PASS:-zenko} \
            --set block_global=false \
            -s /usr/bin/sfko/proxy_addon.py"

if [ -z "$PROXY_MODE" -o "$PROXY_MODE" != "web" ]; then
    PROXY_BIN='mitmdump'
elif [ "$PROXY_MODE" = "web" ]; then
    PROXY_BIN="mitmweb"
    PROXY_OPTS="$PROXY_OPTS --web-iface 0.0.0.0"
fi

su-exec sfko "$PROXY_BIN" $PROXY_OPTS
