{{- range $secret := .Values.secret }}
{{- if $secret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
{{ include "mgob.secret.labels" . | indent 2 }}
type: Opaque
data:
  {{- range $name, $value := $secret.data }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end -}}
{{ end }}
