apiVersion: v1
kind: Service
metadata:
  name: {{ template "mgob.fullname" . }}
  labels:
    name: {{ template "mgob.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: {{ template "mgob.fullname" . }}
  selector:
    app: {{ template "mgob.fullname" . }}
  {{ include "mgob.role" . | indent 2 }}
