{
 "title": "ZooKeeper",
 "description": "ZooKeeper Dashboard",
 "tags": [ "zookeeper" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Instance",
    "query": "label_values({job=\"${job}\",namespace=\"${namespace}\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${job}\",namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "leader_uptime{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ephemerals Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ephemerals_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Znode Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "znode_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "watch_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "znode_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} znode_count"
    },
    {
     "expr": "ephemerals_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} ephemerals"
    }
   ]
  },
  {
   "title": "znode_count_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(znode_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} znode_count_rate"
    },
    {
     "expr": "rate(ephemerals_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} ephemerals_rate"
    }
   ]
  },
  {
   "title": "global_sessions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "global_sessions{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "local_sessions ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "local_sessions{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "write_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "write_per_namespace_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} write_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "read_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "read_per_namespace_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} read_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} approximate_data_size"
    }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packets_received{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} packets_received"
    }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packets_sent{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} packets_sent"
    }
   ]
  },
  {
   "title": "response_packet_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "response_packet_cache_misses{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} response_packet_cache_misses"
    },
    {
     "expr": "response_packet_cache_hits{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} response_packet_cache_hits"
    },
    {
     "expr": "response_packet_get_children_cache_misses{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} response_packet_get_children_cache_misses"
    },
    {
     "expr": "response_packet_get_children_cache_hits{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} response_packet_get_children_cache_hits"
    }
   ]
  },
  {
   "title": "unrecoverable_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unrecoverable_error_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} unrecoverable_error_count"
    }
   ]
  },
  {
   "title": "digest_mismatches_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "digest_mismatches_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} digest_mismatches_count"
    }
   ]
  },
  {
   "title": "startup_snap_load_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "startup_snap_load_time_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} startup_snap_load_time"
    }
   ]
  },
  {
   "title": "startup_txns_loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "startup_txns_loaded_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} startup_txns_loaded"
    }
   ]
  },
  {
   "title": "db_init_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dbinittime_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} db_init_time"
    }
   ]
  },
  {
   "title": "Quorum/Leader Election",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "quorum_size",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(quorum_size{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"})",
       "legendFormat": "quorum_size"
      }
     ]
    },
    {
     "title": "leader",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "format": "ms",
     "valueName": "name",
     "targets": [
      {
       "expr": "leader_uptime{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "leader_uptime",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "leader_uptime{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} leader_uptime"
      }
     ]
    },
    {
     "title": "learner/observer",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "max(learners{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"})",
       "legendFormat": "learners"
      },
      {
       "expr": "max(synced_non_voting_followers{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"})",
       "legendFormat": "synced_non_voting_followers"
      },
      {
       "expr": "max(synced_observers{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"})",
       "legendFormat": "synced_observers"
      }
     ]
    },
    {
     "title": "election_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "election_time_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} election_time_count"
      },
      {
       "expr": "election_time_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} election_time_sum(ms)"
      },
      {
       "expr": "election_time_sum/election_time_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} election_avg_time(ms)"
      }
     ]
    },
    {
     "title": "quorum uptime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "uptime{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} uptime"
      }
     ]
    },
    {
     "title": "learner_commit_received_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "learner_commit_received_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} learner_commit_received_count"
      }
     ]
    },
    {
     "title": "commit_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "commit_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} commit_count"
      }
     ]
    },
    {
     "title": "snap_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "snap_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} snap_count"
      }
     ]
    },
    {
     "title": "diff_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "diff_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} diff_count"
      }
     ]
    },
    {
     "title": "looking_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "looking_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} looking_count"
      }
     ]
    },
    {
     "title": "proposal_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "proposal_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} proposal_count"
      }
     ]
    },
    {
     "title": "proposal_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "last_proposal_size{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} last_proposal_size"
      },
      {
       "expr": "max_proposal_size{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} max_proposal_size"
      },
      {
       "expr": "min_proposal_size{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} min_proposal_size"
      }
     ]
    },
    {
     "title": "follower_sync_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(follower_sync_time_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[1m])",
       "legendFormat": "{{pod}} follower_sync_time"
      }
     ]
    },
    {
     "title": "learner_handler_qp_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "learner_handler_qp_size_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} learner_handler_qp_size_sum sid:{{key}}"
      }
     ]
    },
    {
     "title": "quit_leading_due_to_disloyal_voter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quit_leading_due_to_disloyal_voter{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} quit_leading_due_to_disloyal_voter"
      }
     ]
    },
    {
     "title": "Observer Master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(om_commit_process_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
       "legendFormat": "{{pod}} om_commit_process_time"
      },
      {
       "expr": "rate(om_proposal_process_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
       "legendFormat": "{{pod}} om_proposal_process_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Session/Watch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "watch_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} watch_count"
      }
     ]
    },
    {
     "title": "node_changed_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_changed_watch_count_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} node_changed_watch_count"
      }
     ]
    },
    {
     "title": "node_children_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_children_watch_count_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} node_children_watch_count"
      }
     ]
    },
    {
     "title": "node_deleted_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_deleted_watch_count_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} node_deleted_watch_count"
      }
     ]
    },
    {
     "title": "node_created_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_created_watch_count_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} node_created_watch_count"
      }
     ]
    },
    {
     "title": "revalidate_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "revalidate_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} revalidate_count"
      }
     ]
    },
    {
     "title": "stale_sessions_expired",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "stale_sessions_expired{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} stale_sessions_expired"
      }
     ]
    },
    {
     "title": "dead_watchers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dead_watchers_cleared{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} dead_watchers_cleared"
      },
      {
       "expr": "dead_watchers_queued{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} dead_watchers_queued"
      },
      {
       "expr": "rate(dead_watchers_cleaner_latency_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
       "legendFormat": "{{pod}} dead_watchers_cleaner_latency"
      }
     ]
    },
    {
     "title": "add_dead_watcher_stall_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "add_dead_watcher_stall_time{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} add_dead_watcher_stall_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Client/Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "outstanding_requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "outstanding_requests{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} outstanding_requests"
      }
     ]
    },
    {
     "title": "client_response_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "last_client_response_size{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} last_client_response_size"
      },
      {
       "expr": "min_client_response_size{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} min_client_response_size"
      },
      {
       "expr": "max_client_response_size{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} max_client_response_size"
      }
     ]
    },
    {
     "title": "bytes_received_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bytes_received_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} bytes_received_count"
      }
     ]
    },
    {
     "title": "connection_request_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_request_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} connection_request_count"
      }
     ]
    },
    {
     "title": "num_alive_connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "num_alive_connections{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} num_alive_connections"
      }
     ]
    },
    {
     "title": "connection_rejected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_rejected{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} connection_rejected"
      }
     ]
    },
    {
     "title": "connection_drop_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_drop_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} connection_drop_count"
      }
     ]
    },
    {
     "title": "connection_drop_probability",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_drop_probability{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} connection_drop_probability"
      }
     ]
    },
    {
     "title": "sessionless_connections_expired",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sessionless_connections_expired{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
       "legendFormat": "{{pod}} sessionless_connections_expired"
      }
     ]
    },
    {
     "title": "connection_token_deficit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(connection_token_deficit_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
       "legendFormat": "{{pod}} connection_token_deficit"
      }
     ]
    }
   ]
  },
  { "title": "Disk/Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "open_file_descriptor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "open_file_descriptor_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "fsync_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fsynctime_sum * 1000 /fsynctime_count{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} fsynctime_avg(μs)"
    },
    {
     "expr": "irate(fsynctime_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[1m])",
     "legendFormat": "{{pod}} fsynctime_rate"
    }
   ]
  },
  {
   "title": "snapshot_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(snapshottime_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} snapshot_time_rate"
    }
   ]
  },
  { "title": "Prep_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "prep_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prep_process_time_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} prep_process_time"
    }
   ]
  },
  {
   "title": "prep_processor_queue_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prep_processor_queue_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} prep_processor_queue_time_ms"
    }
   ]
  },
  {
   "title": "prep_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prep_processor_queue_size_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} prep_processor_queue_size"
    }
   ]
  },
  {
   "title": "prep_processor_request_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prep_processor_request_queued{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} prep_processor_request_queued"
    }
   ]
  },
  {
   "title": "outstanding_changes_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_changes_queued{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} outstanding_changes_queued"
    },
    {
     "expr": "outstanding_changes_removed{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} outstanding_changes_removed"
    }
   ]
  },
  {
   "title": "close_session_prep_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(close_session_prep_time_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} close_session_prep_time"
    }
   ]
  },
  { "title": "Sync_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "sync_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_process_time_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} sync_process_time"
    }
   ]
  },
  {
   "title": "sync_processor_queue_flush_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_queue_flush_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} sync_processor_queue_flush_time"
    }
   ]
  },
  {
   "title": "sync_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_queue_size_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} sync_processor_queue_size"
    }
   ]
  },
  {
   "title": "sync_processor_request_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_processor_request_queued{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} sync_processor_request_queued"
    }
   ]
  },
  {
   "title": "sync_processor_batch_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_batch_size_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} sync_processor_batch_size"
    }
   ]
  },
  { "title": "Commit_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "commit_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(commit_process_time_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} commit_process_time"
    },
    {
     "expr": "rate(read_commitproc_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} read_commitproc_time"
    },
    {
     "expr": "rate(write_commitproc_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} write_commitproc_time"
    }
   ]
  },
  {
   "title": "commit_proc_req_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_commit_proc_req_queued_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} write_commit_proc_req_queued"
    },
    {
     "expr": "rate(read_commit_proc_req_queued_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} read_commit_proc_req_queued"
    },
    {
     "expr": "rate(commit_commit_proc_req_queued_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} commit_commit_proc_req_queued"
    }
   ]
  },
  {
   "title": "requests_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(requests_in_session_queue_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} requests_in_session_queue"
    }
   ]
  },
  {
   "title": "commit_proc_issued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(read_commit_proc_issued_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} read_commit_proc_issued"
    },
    {
     "expr": "rate(write_commit_proc_issued_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} write_commit_proc_issued"
    }
   ]
  },
  {
   "title": "concurrent_request_processing_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(concurrent_request_processing_in_commit_processor_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} concurrent_request_processing_in_commit_processor"
    }
   ]
  },
  {
   "title": "time_waiting_empty_pool_in_commit_processor_read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_waiting_empty_pool_in_commit_processor_read_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} time_waiting_empty_pool_in_commit_processor_read"
    }
   ]
  },
  {
   "title": "pending_session_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pending_session_queue_size_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} pending_session_queue_size"
    }
   ]
  },
  {
   "title": "local_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(local_write_committed_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} local_write_committed_time_ms"
    }
   ]
  },
  {
   "title": "server_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(server_write_committed_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} server_write_committed_time"
    }
   ]
  },
  {
   "title": "write_batch_time_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_batch_time_in_commit_processor_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} write_batch_time_in_commit_processor"
    }
   ]
  },
  {
   "title": "reads_after_write_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reads_after_write_in_session_queue_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} reads_after_write_in_session_queue"
    }
   ]
  },
  {
   "title": "session_queues_drained",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(session_queues_drained_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} session_queues_drained"
    }
   ]
  },
  {
   "title": "reads_issued_from_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reads_issued_from_session_queue_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} reads_issued_from_session_queue"
    }
   ]
  },
  {
   "title": "request_commit_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_commit_queued{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} request_commit_queued"
    }
   ]
  },
  { "title": "Final_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "title": "write_final_proc_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_final_proc_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} write_final_proc_time_ms"
    }
   ]
  },
  {
   "title": "read_final_proc_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(read_final_proc_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} read_final_proc_time_ms"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 } },
  {
   "title": "read_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(readlatency_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} readlatency"
    }
   ]
  },
  {
   "title": "update_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(updatelatency_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} updatelatency"
    }
   ]
  },
  {
   "title": "max_min_avg_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max_latency{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} max_latency"
    },
    {
     "expr": "min_latency{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} min_latency"
    },
    {
     "expr": "avg_latency{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} avg_latency"
    }
   ]
  },
  {
   "title": "proposal_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proposal_latency_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} proposal_latency"
    }
   ]
  },
  {
   "title": "quorum_ack_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(quorum_ack_latency_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} quorum_ack_latency"
    }
   ]
  },
  {
   "title": "ack_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ack_latency_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} ack_latency_sum"
    }
   ]
  },
  {
   "title": "propagation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(propagation_latency_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} propagation_latency"
    }
   ]
  },
  {
   "title": "commit_propagation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(commit_propagation_latency_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} commit_propagation_latency"
    }
   ]
  },
  {
   "title": "proposal_ack_creation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "proposal_ack_creation_latency{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} proposal_ack_creation_latency-{{quantile}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 206 } },
  {
   "title": "tls_handshake",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tls_handshake_exceeded{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} tls_handshake_exceeded"
    },
    {
     "expr": "outstanding_tls_handshake{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} outstanding_tls_handshake"
    }
   ]
  },
  {
   "title": "ensemble_auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ensemble_auth_fail{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} ensemble_auth_fail"
    },
    {
     "expr": "ensemble_auth_success{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} ensemble_auth_success"
    },
    {
     "expr": "ensemble_auth_skip{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} ensemble_auth_skip"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 215 } },
  {
   "title": "jvm_classes_loaded",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 216 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_classes_loaded{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 216 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_current{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_deadlocked",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 216 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_deadlocked{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "jvm_pause_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_pause_time_ms_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} jvm_pause_time_ms"
    }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}[5m])",
     "legendFormat": "{{pod}} gc:{{gc}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} state:{{state}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pod=~\"$pod\",job=\"${job}\",namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}} pool:{{pool}}"
    }
   ]
  }
 ]
}