annotations:
  category: Database
apiVersion: v2
appVersion: 5.0.10
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: MongoDB(R) is an open source NoSQL database that uses JSON for data storage.
  MongoDB(TM) Sharded improves scalability and reliability for large datasets by distributing
  data across multiple machines.
home: https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded
icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: mongodb-sharded
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/mongodb-sharded
- https://mongodb.org
version: 5.1.4
