annotations:
  category: Database
  images: |
    - name: mongodb-exporter
      image: docker.io/bitnami/mongodb-exporter:0.40.0-debian-12-r33
    - name: mongodb-sharded
      image: docker.io/bitnami/mongodb-sharded:6.0.13-debian-11-r20
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r22
  licenses: Apache-2.0
apiVersion: v2
appVersion: 6.0.13
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: MongoDB(R) is an open source NoSQL database that uses JSON for data storage.
  MongoDB(TM) Sharded improves scalability and reliability for large datasets by distributing
  data across multiple machines.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: mongodb-sharded
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mongodb-sharded
version: 6.6.7
