# Default values for s3-data.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: zenko/cloudserver
  tag: 8.1.4
  pullPolicy: IfNotPresent
service:
  name: s3-data
  type: ClusterIP
  internalPort: 9991
  externalPort: 9991

## Enable file syncing. If set to 'true', files will not be synced to ensure
## that they are written to disk. Also, it will not be guranteed that page
## caches will be released by the Kernel when 'noCache' is 'true'
noSync: false

## Enable Kernel page caching. If set to 'true', page caches will be released
## after reading or writing files using posix_fadvise(POSIX_FADV_DONTNEED)
## This prevents virtual memory size from increasing proportinally to the files
## read or written.
noCache: true

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  annotations: {}
  existingClaim: ""
  size: 90Gi
  # storageClass: "-"
allowHealthchecksFrom: '0.0.0.0/0'

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
