apiVersion: v1
kind: Service
metadata:
  name: azure-mock
spec:
  selector:
    name: azure-mock
  clusterIP: None
  ports:
    - name: unused
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: azure-mock-pod
  labels:
    name: azure-mock
    component: mock
spec:
  hostname: devstoreaccount1
  subdomain: azure-mock
  containers:
  - image: zenko/azure-mock:latest
    name: azurite
    ports:
      - containerPort: 80
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: azure-mock
spec:
  rules:
  - host: '*.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: http
        path: /
        pathType: Prefix
  - host: 'azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: http
        path: /
        pathType: Prefix
  - host: '*.blob.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: http
        path: /
        pathType: Prefix
  - host: 'blob.azure-mock.zenko.local'
    http:
      paths:
      - backend:
          service:
            name: azure-mock
            port:
              name: http
        path: /
        pathType: Prefix
