apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-operator
  namespace: ${ZOOKEEPER_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-operator
  template:
    metadata:
      labels:
        name: zookeeper-operator
    spec:
      serviceAccountName: zookeeper-operator
      containers:
        - name: zookeeper-operator
          image: ${ZOOKEEPER_IMAGE_PREFIX}/${ZOOKEEPER_IMAGE_NAME}:${ZOOKEEPER_OPERATOR_TAG}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - zookeeper-operator
          imagePullPolicy: Always
          env:
          - name: WATCH_NAMESPACE
            value: "${ZOOKEEPER_WATCH_NAMESPACE}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "zookeeper-operator"
