apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator
  namespace: ${ZOOKEEPER_NAMESPACE}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zookeeper-operator
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zookeeper-operator-role-binding
subjects:
- kind: ServiceAccount
  name: zookeeper-operator
  namespace: default
roleRef:
  kind: Role
  name: zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
