{{- if and (not .Values.configsvr.external.host) .Values.configsvr.pdb.enabled -}}
kind: PodDisruptionBudget
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
metadata:
  name: {{ include "common.names.fullname" . }}-configsvr
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: configsvr
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: configsvr
  {{- if .Values.configsvr.pdb.minAvailable }}
  minAvailable: {{ .Values.configsvr.pdb.minAvailable | int }}
  {{- end }}
  {{- if .Values.configsvr.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.configsvr.pdb.maxUnavailable | int }}
  {{- end }}
{{- end -}}
