kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zenko-offline-cosmos-operator
  labels:
    app: cosmos-operator
    release: zenko-offline
subjects:
- kind: ServiceAccount
  name: zenko-offline-cosmos-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: zenko-offline-cosmos-operator
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zenko-offline-cosmos-operator
  labels:
    app: cosmos-operator
    release: zenko-offline
rules:
- apiGroups: [""]
  resources:
  - persistentvolumes
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zenko-test-cosmos-operator
  labels:
    app: cosmos-operator
    release: zenko-test
subjects:
- kind: ServiceAccount
  name: zenko-test-cosmos-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: zenko-test-cosmos-operator
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zenko-test-cosmos-operator
  labels:
    app: cosmos-operator
    release: zenko-test
rules:
- apiGroups: [""]
  resources:
  - persistentvolumes
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch", "delete"]
