{
 "title": "Kafka Connect",
 "tags": [ "Backeat" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_connect_commit_id_info, instance)"
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": "label_values(kafka_connect_connector_status, connector)"
   }
  ]
 },
 "panels": [
  {
   "title": "Workers",
   "type": "stat",
   "description": "Number of workers available",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${job}\", namespace=\"${namespace}\"})",
     "query": "sum(up{job=\"${job}\", namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Connectors not running",
   "type": "stat",
   "description": "Number of connectors not running",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_status{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) - sum(kafka_connect_connector_status{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", status=\"running\"})",
     "query": "sum(kafka_connect_connector_status{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) - sum(kafka_connect_connector_status{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", status=\"running\"})"
    }
   ]
  },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "query": "sum(kafka_connect_worker_connector_total_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "query": "sum(kafka_connect_worker_connector_running_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "query": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "query": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "query": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "query": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Connector repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_status{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by(status)",
     "legendFormat": "{{status}}",
     "query": "sum(kafka_connect_connector_status{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by(status)"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "running",
     "query": "sum(kafka_connect_worker_connector_running_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "failed",
     "query": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "paused",
     "query": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "unassigned",
     "query": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "destroyed",
     "query": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Status of connectors over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_status{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", status!=\"\"}) by (status)",
     "legendFormat": "{{status}}",
     "query": "sum(kafka_connect_connector_status{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", status!=\"\"}) by (status)"
    }
   ]
  },
  {
   "title": "Status of tasks over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "running",
     "query": "sum(kafka_connect_worker_connector_running_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "failed",
     "query": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "paused",
     "query": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "destroyed",
     "query": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})",
     "legendFormat": "unassigned",
     "query": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"})"
    }
   ]
  },
  { "title": "Connect Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Connect Workers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count(kafka_connect_app_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", start_time_ms!=\"\"}) by (instance, start_time_ms)",
     "query": "count(kafka_connect_app_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", start_time_ms!=\"\"}) by (instance, start_time_ms)"
    },
    {
     "expr": "count(kafka_connect_app_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", version!=\"\"}) by (instance, version)",
     "query": "count(kafka_connect_app_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", version!=\"\"}) by (instance, version)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)",
     "query": "sum(kafka_connect_worker_connector_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_startup_success_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)",
     "query": "sum(kafka_connect_worker_connector_startup_success_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_startup_failure_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)",
     "query": "sum(kafka_connect_worker_connector_startup_failure_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)",
     "query": "sum(kafka_connect_worker_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_task_startup_success_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)",
     "query": "sum(kafka_connect_worker_task_startup_success_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_task_startup_failure_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)",
     "query": "sum(kafka_connect_worker_task_startup_failure_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Network IO Rate",
   "type": "timeseries",
   "description": "Average number of network operations (reads or writes) on all connections per second",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_network_io_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_network_io_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "timeseries",
   "description": "Bytes per second read off all sockets",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_connect_incoming_byte_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_incoming_byte_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "timeseries",
   "description": "Average number of outgoing bytes sent per second to all servers",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_connect_outgoing_byte_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_outgoing_byte_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current number of active connections",
   "type": "timeseries",
   "description": "Current number of active connections",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connection_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_connection_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed authentication connections",
   "type": "timeseries",
   "description": "Connections that failed authentication",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_failed_authentication_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_failed_authentication_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Successful authentication connections",
   "type": "timeseries",
   "description": "Connections that were successfully authenticated using SASL or SSL",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_successful_authentication_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_successful_authentication_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "Average number of requests sent per second",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_request_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_request_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Responses received and sent",
   "type": "timeseries",
   "description": "Responses received and sent per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_response_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_response_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "timeseries",
   "description": "Fraction of time the I/O thread spent doing I/O",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_io_ratio{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_io_ratio{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Connector details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(count(kafka_connect_connector_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", status!=\"\"}) by(instance, status), \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")",
     "query": "label_replace(label_replace(label_replace(count(kafka_connect_connector_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", status!=\"\"}) by(instance, status), \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")"
    },
    {
     "expr": "count(kafka_connect_connector_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", connector_type!=\"\"}) by(instance, connector_type)",
     "query": "count(kafka_connect_connector_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", connector_type!=\"\"}) by(instance, connector_type)"
    },
    {
     "expr": "count(kafka_connect_connector_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", connector_version!=\"\"}) by(instance, connector_version)",
     "query": "count(kafka_connect_connector_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", connector_version!=\"\"}) by(instance, connector_version)"
    },
    {
     "expr": "count(kafka_connect_connector_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", connector_class!=\"\"}) by(instance, connector_class)",
     "query": "count(kafka_connect_connector_info{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", connector_class!=\"\"}) by(instance, connector_class)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)",
     "query": "sum(kafka_connect_worker_connector_total_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)",
     "query": "sum(kafka_connect_worker_connector_running_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)",
     "query": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)",
     "query": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)",
     "query": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)",
     "query": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}) by(instance)"
    }
   ]
  },
  { "title": "Rebalances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Rebalances average time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_rebalance_avg_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "query": "kafka_connect_worker_rebalance_rebalance_avg_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "($instance) Time since last rebalance",
   "type": "stat",
   "description": "Time since last rebalance",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}",
     "query": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Task metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_avg{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_connector_task_batch_size_avg{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "timeseries",
   "description": "Maximum size of the batches processed by the connector",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_max{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_connector_task_batch_size_max{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Offset Commit Success Percentage",
   "type": "timeseries",
   "description": "Average percentage of the task’s offset commit attempts that succeeded",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_offset_commit_success_percentage{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_connector_task_offset_commit_success_percentage{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Offset Commit Average Time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to commit offsets",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_offset_commit_avg_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_connector_task_offset_commit_avg_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Running Ratio ",
   "type": "timeseries",
   "description": "The fraction of time this task has spent in the running state",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_running_ratio{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_connector_task_running_ratio{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  { "title": "Task Errors metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Total record failures",
   "type": "timeseries",
   "description": "Total number of failures seen by task",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_failures{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_task_error_total_record_failures{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "description": "Total number of errors seen by task",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 78 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_errors{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_task_error_total_record_errors{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "description": "Total number of records skipped by task",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 78 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_records_skipped{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_task_error_total_records_skipped{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Total errors logged",
   "type": "timeseries",
   "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_errors_logged{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_task_error_total_errors_logged{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "description": "Total number of retries made by task",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_retries{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_task_error_total_retries{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce Requests",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_requests{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_task_error_deadletterqueue_produce_requests{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce Failures",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_failures{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_task_error_deadletterqueue_produce_failures{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\"}"
    }
   ]
  },
  { "title": "Source metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Poll Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_avg_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_source_task_poll_batch_avg_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  {
   "title": "Poll Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_max_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_source_task_poll_batch_max_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  {
   "title": "Source Record Poll rate",
   "type": "timeseries",
   "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_poll_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_source_task_source_record_poll_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  {
   "title": "Source Record Write rate",
   "type": "timeseries",
   "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_write_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_source_task_source_record_write_rate{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  {
   "title": "Source Record Active Count average",
   "type": "timeseries",
   "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_active_count_avg{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_source_task_source_record_active_count_avg{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  {
   "title": "Source Record Active Count max",
   "type": "timeseries",
   "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_active_count_max{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_source_task_source_record_active_count_max{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  { "title": "Sink metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Partition Count",
   "type": "timeseries",
   "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_partition_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_sink_task_partition_count{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  {
   "title": "Put Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to put a batch of sinks records",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_put_batch_avg_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_sink_task_put_batch_avg_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  {
   "title": "Put Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to put a batch of sinks records",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_put_batch_max_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}",
     "query": "kafka_connect_sink_task_put_batch_max_time_ms{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", connector=~\"$connector\", task!=\"\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}[$__rate_interval])",
     "query": "rate(process_cpu_seconds_total{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) without(area)",
     "legendFormat": "{{instance}}",
     "query": "sum(jvm_memory_used_bytes{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}) without(area)"
    },
    {
     "expr": "jvm_memory_max_bytes{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "{{instance}}",
     "query": "jvm_memory_max_bytes{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\", area=\"heap\"}"
    }
   ]
  },
  {
   "title": "JVM GC Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}[$__rate_interval])) without(gc)",
     "legendFormat": "{{instance}}",
     "query": "sum(rate(jvm_gc_collection_seconds_sum{job=\"${job}\", namespace=\"${namespace}\", instance=~\"$instance\"}[$__rate_interval])) without(gc)"
    }
   ]
  }
 ]
}