#!/bin/sh

if [ -z "$CI_CONF_PREFIX" ]; then
    if [ -z $1 ]; then
        CI_CONF_PREFIX="ci"
    else
        CI_CONF_PREFIX="$1"
    fi
fi

echo "\
--set ${CI_CONF_PREFIX}.AWS_GCP_BACKEND_ACCESS_KEY=$AWS_GCP_BACKEND_ACCESS_KEY \
--set ${CI_CONF_PREFIX}.AWS_GCP_BACKEND_ACCESS_KEY_2=$AWS_GCP_BACKEND_ACCESS_KEY_2 \
--set ${CI_CONF_PREFIX}.AWS_GCP_BACKEND_SECRET_KEY=$AWS_GCP_BACKEND_SECRET_KEY \
--set ${CI_CONF_PREFIX}.AWS_GCP_BACKEND_SECRET_KEY_2=$AWS_GCP_BACKEND_SECRET_KEY_2 \
--set ${CI_CONF_PREFIX}.AWS_S3_BACKBEAT_ACCESS_KEY=$AWS_S3_BACKBEAT_ACCESS_KEY \
--set ${CI_CONF_PREFIX}.AWS_S3_BACKBEAT_SECRET_KEY=$AWS_S3_BACKBEAT_SECRET_KEY \
--set ${CI_CONF_PREFIX}.AWS_S3_BACKBEAT_BUCKET_NAME=$AWS_S3_BACKBEAT_BUCKET_NAME \
--set ${CI_CONF_PREFIX}.AWS_S3_BACKEND_ACCESS_KEY=$AWS_S3_BACKEND_ACCESS_KEY \
--set ${CI_CONF_PREFIX}.AWS_S3_BACKEND_ACCESS_KEY_2=$AWS_S3_BACKEND_ACCESS_KEY_2 \
--set ${CI_CONF_PREFIX}.AWS_S3_BACKEND_SECRET_KEY=$AWS_S3_BACKEND_SECRET_KEY \
--set ${CI_CONF_PREFIX}.AWS_S3_BACKEND_SECRET_KEY_2=$AWS_S3_BACKEND_SECRET_KEY_2 \
--set ${CI_CONF_PREFIX}.AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME \
--set ${CI_CONF_PREFIX}.AWS_S3_BUCKET_NAME_2=$AWS_S3_BUCKET_NAME_2 \
--set ${CI_CONF_PREFIX}.AZURE_BACKBEAT_CONTAINER_NAME=$AZURE_BACKBEAT_CONTAINER_NAME \
--set ${CI_CONF_PREFIX}.AZURE_BACKEND_ACCESS_KEY=$AZURE_BACKEND_ACCESS_KEY \
--set ${CI_CONF_PREFIX}.AZURE_BACKEND_ACCESS_KEY_2=$AZURE_BACKEND_ACCESS_KEY_2 \
--set ${CI_CONF_PREFIX}.AZURE_BACKEND_ACCOUNT_NAME=$AZURE_BACKEND_ACCOUNT_NAME \
--set ${CI_CONF_PREFIX}.AZURE_BACKEND_ACCOUNT_NAME_2=$AZURE_BACKEND_ACCOUNT_NAME_2 \
--set ${CI_CONF_PREFIX}.AZURE_BACKEND_CONTAINER_NAME=$AZURE_BACKEND_CONTAINER_NAME \
--set ${CI_CONF_PREFIX}.AZURE_BACKEND_CONTAINER_NAME_2=$AZURE_BACKEND_CONTAINER_NAME_2 \
--set ${CI_CONF_PREFIX}.AZURE_BACKEND_ENDPOINT=$AZURE_BACKEND_ENDPOINT \
--set ${CI_CONF_PREFIX}.AZURE_BACKEND_ENDPOINT_2=$AZURE_BACKEND_ENDPOINT_2 \
--set ${CI_CONF_PREFIX}.GCP_BUCKET_NAME=$GCP_BUCKET_NAME \
--set ${CI_CONF_PREFIX}.GCP_BUCKET_NAME_2=$GCP_BUCKET_NAME_2 \
--set ${CI_CONF_PREFIX}.GCP_CRR_BUCKET_NAME=$GCP_CRR_BUCKET_NAME \
--set ${CI_CONF_PREFIX}.GCP_CRR_MPU_BUCKET_NAME=$GCP_CRR_MPU_BUCKET_NAME \
--set ${CI_CONF_PREFIX}.GCP_MPU_BUCKET_NAME=$GCP_MPU_BUCKET_NAME \
--set ${CI_CONF_PREFIX}.GCP_MPU_BUCKET_NAME_2=$GCP_MPU_BUCKET_NAME_2 \
--set ${CI_CONF_PREFIX}.AWS_S3_BACKBEAT_SRC_BUCKET_NAME=$AWS_S3_BACKBEAT_SRC_BUCKET_NAME \
--set ${CI_CONF_PREFIX}.GCP_CRR_SRC_BUCKET_NAME=$GCP_CRR_SRC_BUCKET_NAME \
--set ${CI_CONF_PREFIX}.AZURE_BACKBEAT_SRC_CONTAINER_NAME=$AZURE_BACKBEAT_SRC_CONTAINER_NAME"
