apiVersion: v1
kind: Pod
metadata:
  name: "zenko-doc-buider"
spec:
  containers:
  - name: worker
    image: {{ images['doc-builder'] }}
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
    command: ["/bin/sh"]
    args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
