{{- if .Values.reporting.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "zenko.reporting" . }}-count-items
  labels:
{{ include "zenko.labels.standard" . | indent 4 }}
spec:
  schedule: "{{ .Values.reporting.countItems.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.reporting.successfulJobsHistory }}
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: count-items
            image: {{ .Values.s3Utils.image.repository }}:{{ .Values.s3Utils.image.tag }}
            imagePullPolicy: {{ .Values.s3Utils.image.pullPolicy }}
            command: ["/bin/bash"]
            args:
            - -c
            - node countItems.js
            env:
            - name: MONGODB_REPLICASET
              value: "{{ template "zenko.mongodb-hosts" . }}"
{{- end -}}
