---
name: "Archive artifact logs and data"
description: "Archive logs, pods and events"

runs:
  using: composite
  steps:
    - name: Archive artifact logs and data
      shell: bash
      run: |-
        set -exu;
        mkdir -p /tmp/artifacts/data/${STAGE}/kind-logs;
        kubectl get pods -A -o yaml > /tmp/artifacts/data/${STAGE}/kind-logs/all-pods.log;
        kubectl get events -A -o yaml > /tmp/artifacts/data/${STAGE}/kind-logs/all-events.log;
        kind export logs /tmp/artifacts/data/${STAGE}/kind-logs/kind-export;
        tar zcvf /tmp/artifacts/${{ github.sha }}-${STAGE}-logs-volumes.tgz /tmp/artifacts/data/${STAGE}/kind-logs;
    - name: Dump kafka
      shell: bash
      run: |-
        set -exu

        NAMESPACE=${NAMESPACE:-default}
        KAFKA=$(kubectl get pods -n ${NAMESPACE} -lkafka_cr=${ZENKO_NAME:-end2end}-base-queue -o jsonpath='{.items[0].metadata.name}')

        kubectl exec -in ${NAMESPACE} ${KAFKA} -c kafka -- \
            env KAFKA_OPTS= kafka-topics.sh --bootstrap-server :9092 --list \
            > /tmp/artifacts/data/${STAGE}/kafka-topics.log

        kubectl exec -in ${NAMESPACE} ${KAFKA} -c kafka -- \
            env KAFKA_OPTS= kafka-consumer-groups.sh --bootstrap-server :9092 --list \
            > /tmp/artifacts/data/${STAGE}/kafka-consumer-groups.log

        kubectl exec -in ${NAMESPACE} ${KAFKA} -c kafka  -- \
                   env KAFKA_OPTS= kafka-consumer-groups.sh --bootstrap-server :9092 --describe --all-groups \
                   > /tmp/artifacts/data/${STAGE}/kafka-offsets.log

        cat /tmp/artifacts/data/${STAGE}/kafka-topics.log | xargs -P 15 -I {} \
            sh -c "kubectl exec -in ${NAMESPACE} ${KAFKA} -c kafka -- \
                   env KAFKA_OPTS= kafka-console-consumer.sh --bootstrap-server :9092 --topic {} \
                                                             --from-beginning --timeout-ms 60000 \
                   > /tmp/artifacts/data/${STAGE}/kafka-messages-{}.log"
