---
name: "Archive artifact logs and data"
description: "Archive logs, pods and events"

runs:
  using: composite
  steps:
    - name: Archive artifact logs and data
      shell: bash
      run: |-
        set -exu;
        mkdir -p /tmp/artifacts/data/kind-logs;
        kubectl get pods -A -o yaml > /tmp/artifacts/data/kind-logs/all-pods.log;
        kubectl get events -A -o yaml > /tmp/artifacts/data/kind-logs/all-events.log;
        kind export logs /tmp/artifacts/data/kind-logs/kind-export;
        tar zcvf /tmp/artifacts/${{ github.sha }}-${STAGE}-logs-volumes.tgz /tmp/artifacts/data/kind-logs;
      env:
         STAGE: end2end-http
