{
 "title": "Redis",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [ "redis" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"${namespace}\", job=\"${job}\"})",
     "query": "sum(up{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))",
     "query": "max(max_over_time(redis_uptime_in_seconds{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))",
     "query": "sum(rate(redis_commands_processed_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(redis_keyspace_hits_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "hits",
     "query": "sum(irate(redis_keyspace_hits_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(irate(redis_keyspace_misses_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "misses",
     "query": "sum(irate(redis_keyspace_misses_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{namespace=\"${namespace}\", job=\"${job}\"})",
     "query": "sum(redis_db_keys{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=\"${namespace}\", job=\"${job}\"})",
     "query": "sum(redis_connected_clients{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{namespace=\"${namespace}\", job=\"${job}\"})",
     "legendFormat": "used",
     "query": "sum(redis_memory_used_bytes{namespace=\"${namespace}\", job=\"${job}\"})"
    },
    {
     "expr": "sum(irate(redis_keyspace_misses_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "max",
     "query": "sum(irate(redis_keyspace_misses_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "input",
     "query": "sum(rate(redis_net_input_bytes_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "output",
     "query": "sum(rate(redis_net_output_bytes_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"${namespace}\", job=\"${job}\"}) by (db)",
     "legendFormat": "{{ db }}",
     "query": "sum (redis_db_keys{namespace=\"${namespace}\", job=\"${job}\"}) by (db)"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"${namespace}\", job=\"${job}\"}) - sum (redis_db_keys_expiring{namespace=\"${namespace}\", job=\"${job}\"})",
     "legendFormat": "not expiring",
     "query": "sum (redis_db_keys{namespace=\"${namespace}\", job=\"${job}\"}) - sum (redis_db_keys_expiring{namespace=\"${namespace}\", job=\"${job}\"})"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=\"${namespace}\", job=\"${job}\"})",
     "legendFormat": "expiring",
     "query": "sum (redis_db_keys_expiring{namespace=\"${namespace}\", job=\"${job}\"})"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval])) by (addr)",
     "legendFormat": "expired",
     "query": "sum(rate(redis_expired_keys_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval])) by (addr)"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval])) by (addr)",
     "legendFormat": "evicted",
     "query": "sum(rate(redis_evicted_keys_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval])) by (addr)"
    }
   ]
  },
  {
   "title": "Top5 commands with most Calls/sec",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(irate(redis_commands_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval])) by (cmd))",
     "legendFormat": "{{ cmd }}",
     "query": "topk(5, sum(irate(redis_commands_total{namespace=\"${namespace}\", job=\"${job}\"}[$__rate_interval])) by (cmd))"
    }
   ]
  }
 ]
}