version: "0.2"

branches:
  feature/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*:
    stage: pre-merge

models:
  - Git: &git_pull
      name: git pull
      repourl: "%(prop:git_reference)s"
      mode: full
      method: clobber
      retryFetch: true
      haltOnFailure: true
  - Upload: &upload_artifacts
      source: tests/artifacts
      urls:
        - "*"
  - ShellCommand: &private_registry_login
      name: Private Registry Login
      command: >
        docker login
        -u '%(secret:private_registry_username)s'
        -p '%(secret:private_registry_password)s'
        '%(secret:private_registry_url)s'
  - ShellCommand: &helm_lint
      name: Lint charts
      command: >
        helm lint kubernetes/zenko/ &&
        helm lint kubernetes/zenko/charts/*
      haltOnFailure: true
  - ShellCommand: &dump_logs
      name: Dump zenko logs
      command: make -e dump-logs
      workdir: build/tests
      env:
        HELM_NAMESPACE: '%(prop:testNamespace)s'
  - env: &secrets_env # contains values used for test config
      AWS_ACCESS_KEY: '%(secret:aws_s3_backend_access_key)s'
      AWS_SECRET_KEY: '%(secret:aws_s3_backend_secret_key)s'
      AWS_ACCESS_KEY_2: '%(secret:aws_s3_backend_access_key_2)s'
      AWS_SECRET_KEY_2: '%(secret:aws_s3_backend_secret_key_2)s'

      GCP_ACCESS_KEY: '%(secret:aws_gcp_backend_access_key)s'
      GCP_SECRET_KEY: '%(secret:aws_gcp_backend_secret_key)s'
      GCP_ACCESS_KEY_2: '%(secret:aws_gcp_backend_access_key_2)s'
      GCP_SECRET_KEY_2: '%(secret:aws_gcp_backend_secret_key_2)s'

      AZURE_ACCOUNT_NAME: '%(secret:azure_backend_account_name)s'
      AZURE_BACKEND_ENDPOINT: '%(secret:azure_backend_endpoint)s'
      AZURE_SECRET_KEY: '%(secret:azure_backend_access_key)s'
      AZURE_ACCOUNT_NAME_2: '%(secret:azure_backend_account_name_2)s'
      AZURE_BACKEND_ENDPOINT_2: '%(secret:azure_backend_endpoint_2)s'
      AZURE_SECRET_KEY_2: '%(secret:azure_backend_access_key_2)s'
      ZENKO_ACCESS_KEY: HEYIMAACCESSKEY
      ZENKO_SECRET_KEY: loOkAtMEImASecRetKEy123=
      AWS_BACKEND_SOURCE_LOCATION: awsbackend
      AWS_BACKEND_DESTINATION_LOCATION: awsbackendmismatch
      GCP_BACKEND_DESTINATION_LOCATION: gcpbackendmismatch
      AZURE_BACKEND_DESTINATION_LOCATION: azurebackendmismatch
      LOCATION_QUOTA_BACKEND: quotabackend
      GCP_BACKEND_SERVICE_KEY: '%(secret:gcp_backend_service_key)s'
      GCP_BACKEND_SERVICE_EMAIL: '%(secret:gcp_backend_service_email)s'
      COSBENCH_NIGHTLY_SERVICE_ACCOUNT: '%(secret:cosbenchNightlyServiceAccount)s'
      COSBENCH_SPREADSHEET_ID: '%(secret:cosbenchSpreadsheetID)s'

      AWS_BUCKET_NAME: ci-zenko-aws-target-bucket
      AWS_BUCKET_NAME_2: ci-zenko-aws-target-bucket-2
      AWS_CRR_BUCKET_NAME: ci-zenko-aws-crr-target-bucket
      AWS_CRR_SRC_BUCKET_NAME: ci-zenko-aws-crr-src-bucket

      AZURE_BUCKET_NAME: ci-zenko-azure-target-bucket
      AZURE_BUCKET_NAME_2: ci-zenko-azure-target-bucket-2
      AZURE_CRR_BUCKET_NAME: ci-zenko-azure-crr-target-bucket
      AZURE_CRR_SRC_BUCKET_NAME: ci-zenko-azure-crr-src-bucket

      GCP_BUCKET_NAME: ci-zenko-gcp-target-bucket
      GCP_BUCKET_NAME_2: ci-zenko-gcp-target-bucket-2
      GCP_CRR_BUCKET_NAME: ci-zenko-gcp-crr-target-bucket
      GCP_CRR_MPU_BUCKET_NAME: ci-zenko-gcp-crr-mpu-bucket
      GCP_CRR_SRC_BUCKET_NAME: ci-zenko-gcp-crr-src-bucket
      GCP_MPU_BUCKET_NAME: ci-zenko-gcp-mpu-bucket
      GCP_MPU_BUCKET_NAME_2: ci-zenko-gcp-mpu-bucket-2
      MULTI_CRR_SRC_BUCKET_NAME: ci-zenko-multi-crr-src-bucket
      TRANSIENT_SRC_BUCKET_NAME: ci-zenko-transient-src-bucket

  - env: &docker_env # contains values for build test images
      E2E_DOCKER_IMAGE_NAME: '%(secret:private_registry_url)s/zenko/zenko-e2e'
      BACKBEAT_DOCKER_IMAGE_NAME: '%(secret:private_registry_url)s/zenko/backbeat-e2e'
      IMAGE_REGISTRY: '%(secret:private_registry_url)s'
      TAG_OVERRIDE: '%(prop:commit_short_revision)s'

  - env: &k8s_env # containes values for running helm and kubectl
      ZENKO_HELM_RELEASE: 'zenko-test'
      HELM_NAMESPACE: '%(prop:testNamespace)s'
      TILLER_NAMESPACE: '%(prop:testNamespace)s'
      INSTALL_TIMEOUT: "600"

  - env: &global_env # contains all env values
      <<: [*secrets_env, *docker_env, *k8s_env]

stages:
  pre-merge:
    worker:
      type: local
    steps:
   # - TriggerStages:
   #     name: Build documentation
   #     haltOnFailure: true
   #     stage_names:
   #     - build-doc
    - TriggerStages:
        name: trigger all the tests
        stage_names:
        #- online-zenko
        - offline-zenko

  build-doc:
    worker:
      type: kube_pod
      path: eve/workers/doc-builder.yaml
      images:
        doc-builder:
          context: '.'
          dockerfile: docs/Dockerfile
    steps:
    - Git: *git_pull
    - ShellCommand:
        name: 'Build doc'
        haltOnFailure: true
        command: tox --workdir /tmp/tox -e docs -- html # latexpdf

  offline-zenko:
    worker:
      type: kube_pod
      path: eve/workers/zenko.yaml
    steps:
    - Git: *git_pull
    - ShellCommand:
        name: Kubeconfig
        command: |
          set -ex
          rm -rf /root/.kube
          mkdir -p /root/.kube
          echo "$CI_KUBECONFIG" | envsubst > /root/.kube/config
          head /root/.kube/config
          sleep 5
        env:
          CI_KUBECONFIG: '%(secret:openstack_cluster_conf)s'
          NAMESPACE: '%(prop:workername)s'
    - ShellCommand:
        name: Create namespace
        command: |
          if ping -q -w 1 -s 1 $CLUSTER_IP ; then
            sleep 5
            echo $KUBECONFIG
            ls ~/.kube
            kubectl config view
            KUBECONFIG=$KUBECONFIG
            kubectl config get-contexts --kubeconfig $KUBECONFIG
            kubectl config use-context admin-cluster.local || exit 1
            kubectl get ns
            kubectl create namespace '%(prop:workername)s'
            kubectl create rolebinding view-configmap \
            --clusterrole=cluster-admin \
            --serviceaccount='%(prop:workername)s:default' \
            --namespace='%(prop:workername)s'
          else
            apk add bind-tools
            dig +short myip.opendns.com @resolver1.opendns.com
            exit 1
          fi
        env:
          KUBECONFIG: /root/.kube/config
          CLUSTER_IP: '%(secret:openstack_cluster_ip)s'
    - ShellCommand: *private_registry_login
    - ShellCommand:
        name: Cluster Login registry
        command: ./cluster-registry-secret.sh
        workdir: build/eve
        env:
          NAMESPACE: '%(prop:workername)s'
    - ShellCommand:
        name: Setup and run e2e
        command: make -e VERBOSE=1 test || (sleep 600 ; exit 1)
        workdir: build/tests
        env:
          <<: [*secrets_env, *docker_env]
          KUBECONFIG: /root/.kube/config
          ZENKO_HELM_RELEASE: 'zenko-offline'
          HELM_NAMESPACE: '%(prop:workername)s'
          TILLER_NAMESPACE: '%(prop:workername)s'
          INSTALL_TIMEOUT: "600"
    - ShellCommand:
        name: Cleanup
        command: |
          kubectl delete namespace '%(prop:workername)s'
          helm delete $ZENKO_HELM_RELEASE --tiller-namespace $HELM_NAMESPACE
        alwaysRun: true
        sigtermTime: 1200
        env:
          KUBECONFIG: /root/.kube/config
          ZENKO_HELM_RELEASE: 'zenko-offline'
          HELM_NAMESPACE: '%(prop:workername)s'

  online-zenko:
    worker: &kube_cluster
      type: kube_pod
      path: eve/workers/zenko.yaml
      service:
        requests:
          version: "1.10.4"
        namespaces:
        - "testNamespace"    # <<< the default namespace for that stage
    steps:
      - Git: *git_pull
      - ShellCommand: *private_registry_login
      - ShellCommand:
          name: Setup Zenko and run end to end tests
          command: make -e VERBOSE=1 test
          workdir: build/tests
          env:
            <<: *global_env
      - ShellCommand: *dump_logs
      - Upload: *upload_artifacts

  test-latest-zenko:
    worker: *kube_cluster
    steps:
      - Git: *git_pull
      - ShellCommand: *private_registry_login
      - ShellCommand:
          name: Setup latest Zenko and run end to end tests
          command: make -e test-latest
          workdir: build/tests
          env:
            <<: *global_env
      - ShellCommand: *dump_logs
      - Upload: *upload_artifacts

  cosbench-latest:
    worker: *kube_cluster
    steps:
      - Git: *git_pull
      - ShellCommand: *private_registry_login
      - ShellCommand:
          name: Setup and run benchmarks
          command: make -e test-cosbench
          workdir: build/tests
          maxTime: 43200
          env:
            <<: *global_env
      - ShellCommand: *dump_logs
      - Upload: *upload_artifacts
