apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-replicaset-entrypoint
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  mongos-entrypoint.sh: |-
    #!/bin/bash

    . /liblog.sh

    # Disable MongoSH telemtry to support offline deployments
    mongosh --nodb --eval "disableTelemetry()"
    info "MongoDB Telemetry is now disabled."

    exec /entrypoint.sh /run.sh
  replicaset-entrypoint.sh: |-
    #!/bin/bash

    sleep 5

    . /liblog.sh

    # Perform adaptations depending on the host name
    if [[ $HOSTNAME =~ (.*)-0$ ]]; then
      info "Setting node as primary"
      export MONGODB_REPLICA_SET_MODE=primary
    else
      info "Setting node as secondary"
      export MONGODB_REPLICA_SET_MODE=secondary
      {{- if .Values.usePasswordFile }}
      export MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD_FILE="$MONGODB_ROOT_PASSWORD_FILE"
      unset MONGODB_ROOT_PASSWORD_FILE
      {{- else }}
      export MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD="$MONGODB_ROOT_PASSWORD"
      unset MONGODB_ROOT_PASSWORD
      {{- end }}
    fi

    # Disable MongoSH telemtry to support offline deployments
    mongosh --nodb --eval "disableTelemetry()"
    info "MongoDB Telemetry is now disabled."

    exec /entrypoint.sh /run.sh
