{{- if .Values.maintenance.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zenko.retry" . }}
  labels:
{{ include "zenko.labels.standard" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.maintenance.accessKey }}
  accesskey: {{ .Values.maintenance.accessKey | b64enc | quote }}
  {{- else }}
  accesskey: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.maintenance.secretKey }}
  secretkey: {{ .Values.maintenance.secretKey | b64enc | quote }}
  {{- else }}
  secretkey: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
