{{- if and .Values.maintenance.enabled (and .Values.maintenance.accessKey .Values.maintenance.secretKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zenko.retry" . }}
  labels:
{{ include "zenko.labels.standard" . | indent 4 }}
type: Opaque
data:
  accesskey: {{ .Values.maintenance.accessKey | b64enc }}
  secretkey: {{ .Values.maintenance.secretKey | b64enc }}
{{- end -}}
