apiVersion: v1
kind: Service
metadata:
  name: {{ template "zenko-nfs.fullname" . }}
  labels:
    app: {{ template "zenko-nfs.name" . }}
    chart: {{ template "zenko-nfs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: nfs
      port: 2049
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: {{ template "zenko-nfs.name" . }}
    release: {{ .Release.Name }}
