{
 "title": "Cloudserver",
 "description": "Prometheus metrics obtained from Cloudserver",
 "tags": [
  "cloudserver",
  "prometheus"
 ],
 "time": { "from": "2018-08-24T19:23:30.943Z", "to": "2018-08-24T19:33:30.943Z" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(up{app=\"cloudserver\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Node.js Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=\"$pod\"}",
     "legendFormat": "total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=\"$pod\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nodejs_active_requests_total{instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "External Memory",
   "type": "graph",
   "description": "Memory usage of C++ objects bound to JavaScript objects managed by V8",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{instance=\"$pod\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nodejs_version_info{instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=\"$pod\"}"
    }
   ]
  },
  { "title": "Process Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Start time of the process",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "singlestat",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "System CPU Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_system_seconds_total{instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "User CPU Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_user_seconds_total{app=\"cloudserver\"}"
    }
   ]
  },
  {
   "title": "Process Heap",
   "type": "graph",
   "description": "Process heap size in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_heap_bytes{instance=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Resident and virtual memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$pod\"}",
     "legendFormat": "virtual"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$pod\"}",
     "legendFormat": "resident"
    }
   ]
  }
 ]
}