{{- if .Values.global.orbit.enabled -}}
{{- if .Values.ingestion.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "backbeat.fullname" . }}-ingestion-consumer
  labels:
    app: {{ template "backbeat.name" . }}-ingestion
    chart: {{ template "backbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ingestion.consumer.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "backbeat.name" . }}-ingestion
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "backbeat.name" . }}-ingestion
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: ingestion-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          command: ["/usr/src/app/docker-entrypoint.sh"]
          args: ["npm", "run", "mongo_queue_processor"]
          env:
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "{{- if .Values.global.orbit.enabled }}0{{- else }}1{{- end }}"
            - name: KAFKA_HOSTS
              value: "{{- printf "%s-zenko-queue:9092" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: LOG_LEVEL
              value: {{ .Values.logging.level }}
            - name: MONGODB_HOSTS
              value: "{{ template "backbeat.mongodb-hosts" . }}"
            - name: MONGODB_RS
              value: "{{ default "rs0" .Values.mongodb.replicaSet }}"
            - name: EXTENSIONS_INGESTION_AUTH_TYPE
              value: service
            - name: EXTENSIONS_INGESTION_AUTH_ACCOUNT
              value: service-md-ingestion
            - name: REDIS_SENTINELS
              value: "{{ template "backbeat.redis-hosts" . }}"
            - name: REDIS_HA_NAME
              value: "{{ .Values.redis.sentinel.name }}"
            - name: CLOUDSERVER_HOST
              value: "{{- printf "%s-cloudserver" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: CLOUDSERVER_PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path.liveness }}
              port: {{ .Values.health.port }}
          resources:
{{ toYaml .Values.ingestion.consumer.resources | indent 12 }}
    {{- with .Values.ingestion.consumer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ingestion.consumer.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ingestion.consumer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
{{- end -}}
