{{- $dst := merge (default .Values.rclone.destination .Values.rclone.remote) .Values.rclone.destination }}
{{- if not $dst.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cosmos.rclone.fullname" . }}
  labels:
{{ include "cosmos.labels" . | indent 4 }}
type: Opaque
data:
  accessKey: {{ $dst.accessKey | b64enc }}
  secretKey: {{ $dst.secretKey | b64enc }}
{{- end -}}
