{
 "title": "Zenko Overview",
 "tags": [
  "cloudserver",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Detailed",
    "label": "node",
    "query": "label_values(up{app=\"cloudserver\"}, host_node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Data Ingested",
   "type": "singlestat",
   "description": "This is the cumulative size of the data ingested into Zenko.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "abs(ceil(sum(increase(cloud_server_data_ingested{app=\"cloudserver\"}[30d]))))"
    }
   ]
  },
  {
   "title": "Data Requested",
   "type": "singlestat",
   "description": "This is the cumulative size of requested data through Zenko.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "abs(sum(increase(cloud_server_http_request_size_bytes_sum{app=\"cloudserver\"}[30d])))"
    }
   ]
  },
  {
   "title": "Cloudserver CPU Usage",
   "type": "graph",
   "description": "This displays the estimated CloudServer CPU usage per Kubernetes node. Note: 100% usage means an 1 cpu core is being utilized. So you may see up core count x 100",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (host_node) (irate(process_cpu_user_seconds_total{app=\"cloudserver\"}[2m]))) + (sum by (host_node) (irate(process_cpu_system_seconds_total{app=\"cloudserver\"}[2m])))",
     "legendFormat": "{{host_node}}"
    }
   ]
  },
  {
   "title": "Live Operations/s",
   "type": "singlestat",
   "description": "The live number of requests",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum(abs(irate(cloud_server_http_requests_total{app=~\"cloudserver\"}[2m]))))",
     "legendFormat": "Operations per second"
    }
   ]
  },
  {
   "title": "Live RClone Operations/s",
   "type": "singlestat",
   "description": "The live OOB put operations",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum(abs(irate(cloud_server_number_of_ingested_objects{app=\"cloudserver\"}[2m]))))",
     "legendFormat": "Operations per second"
    }
   ]
  },
  {
   "title": "Ingress - Live",
   "type": "singlestat",
   "description": "Speed of data coming into Zenko",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((sum by (instance)(rate({__name__=\"cloud_server_http_request_size_bytes_sum\",app=\"cloudserver\"}[2m]))))"
    }
   ]
  },
  {
   "title": "Egress - Live",
   "type": "singlestat",
   "description": "Speed of data going out of Zenko",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((sum by (instance)(rate({__name__=\"cloud_server_http_response_size_bytes_sum\",app=\"cloudserver\"}[2m]))))"
    }
   ]
  },
  {
   "title": "Average Operations/s",
   "type": "singlestat",
   "description": "Average numbers of operations per second over the current time range",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(sum(abs(rate(cloud_server_http_requests_total{app=~\"cloudserver\"}[30m]))))",
     "legendFormat": "Operations per second"
    }
   ]
  },
  {
   "title": "Average RClone Operations/s",
   "type": "singlestat",
   "description": "The average OOB put operations per second over the selected time range",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(sum(rate(cloud_server_number_of_ingested_objects{app=\"cloudserver\"}[30m])))",
     "legendFormat": "Operations per second"
    }
   ]
  },
  {
   "title": "Ingress/Egress",
   "type": "graph",
   "description": "Speed of data coming in and out of Zenko",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum((sum by (instance)(rate({__name__=~\"cloud_server_http_.*_size_bytes_sum\",app=\"cloudserver\"}[2m]))))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum((sum by (instance)(rate({__name__=~\"cloud_server_http_request_size_bytes_sum\",app=\"cloudserver\"}[2m]))))",
     "legendFormat": "Ingress"
    },
    {
     "expr": "sum((sum by (instance)(rate({__name__=~\"cloud_server_http_response_size_bytes_sum\",app=\"cloudserver\"}[2m]))))",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "Total Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Objects" }
   ],
   "targets": [
    {
     "expr": "sum(delta(cloud_server_number_of_objects{app=\"cloudserver\"}[30d]))",
     "legendFormat": "Total Objects"
    },
    {
     "expr": "sum(delta(cloud_server_number_of_ingested_objects{app=\"cloudserver\"}[30d]))",
     "legendFormat": "Ingested Objects"
    }
   ]
  },
  {
   "title": "HTTP Operations",
   "type": "graph",
   "description": "Displays a graph of all the HTTP operations with 200 codes.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ops", "label": "Operations Per Second" }
   ],
   "targets": [
    {
     "expr": "avg(sum(abs(irate(cloud_server_http_requests_total{app=~\"cloudserver\"}[30m]))))",
     "legendFormat": "Cumulative Requests"
    },
    {
     "expr": "avg(sum(abs(irate(cloud_server_number_of_ingested_objects{app=\"cloudserver\"}[30m]))))",
     "legendFormat": "RClone Ingestion"
    },
    {
     "expr": "avg(sum(abs(irate(cloud_server_http_requests_total{method=\"HEAD\",app=~\"cloudserver\"}[30m]))))",
     "legendFormat": "HEAD Requests"
    },
    {
     "expr": "avg(sum(abs(irate(cloud_server_http_requests_total{method=\"PUT\",app=~\"cloudserver\"}[30m]))))",
     "legendFormat": "PUT Requests"
    },
    {
     "expr": "avg(sum(abs(irate(cloud_server_http_requests_total{method=\"GET\",app=~\"cloudserver\"}[30m]))))",
     "legendFormat": "GET Requests"
    },
    {
     "expr": "avg(sum(abs(irate(cloud_server_http_requests_total{method=\"DELETE\",app=~\"cloudserver\"}[30m]))))",
     "legendFormat": "Delete Requests"
    }
   ]
  }
 ]
}