apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cosmos-operator.fullname" . }}
  labels:
    app: {{ template "cosmos-operator.name" . }}
    chart: {{ template "zenko.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
