{{- if .Values.ingestion.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "backbeat.fullname" . }}-ingestion-consumer
  labels:
    app: {{ template "backbeat.name" . }}-ingestion
    chart: {{ template "backbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ingestion.consumer.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "backbeat.name" . }}-ingestion
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: ingestion-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/src/app/docker-entrypoint.sh"]
          args: ["npm", "run", "mongo_queue_processor"]
          env:
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "{{- if .Values.orbit.enabled }}0{{- else }}1{{- end }}"
            - name: ZOOKEEPER_AUTO_CREATE_NAMESPACE
              value: "1"
            - name: ZOOKEEPER_CONNECTION_STRING
              value: "{{- printf "%s-zenko-quorum:2181" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: KAFKA_HOSTS
              value: "{{- printf "%s-zenko-queue:9092" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: LOG_LEVEL
              value: {{ .Values.logging.level }}
            - name: MONGODB_HOSTS
              value: "{{ template "backbeat.mongodb-hosts" . }}"
            - name: MONGODB_RS
              value: "{{ default "rs0" .Values.mongodb.replicaSet }}"
            - name: MONGODB_DATABASE
              value: "mongodb"
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path.liveness }}
              port: {{ .Values.health.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.health.path.readiness }}
              port: {{ .Values.health.port }}
          resources:
{{ toYaml .Values.ingestion.consumer.resources | indent 12 }}
    {{- with .Values.ingestion.consumer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ingestion.consumer.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ingestion.consumer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
