{
 "title": "Cloudserver",
 "description": "Metrics obtained from Cloudserver pods",
 "tags": [ "cloudserver" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Time Alive",
   "type": "singlestat",
   "description": "Start time of the process.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (process_start_time_seconds{app=\"cloudserver-front\"})"
    }
   ]
  },
  {
   "title": "Node Version",
   "type": "singlestat",
   "description": "Node.js version info.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "nodejs_version_info" }
   ]
  },
  { "title": "NodeJS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "External Memory",
   "type": "graph",
   "description": "Nodejs external memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nodejs_external_memory_bytes" }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "description": "The number of active requests.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    { "expr": "nodejs_active_requests_total" }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "description": "The number of active handles.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles_total" }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "description": "Process heap size from node.js in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes" }
   ]
  },
  { "title": "Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Resident Memory",
   "type": "graph",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"cloudserver-front\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "description": "Virtual memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{app=\"cloudserver-front\"}"
    }
   ]
  },
  {
   "title": "Process Heap",
   "type": "graph",
   "description": "Process heap size in bytes.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_heap_bytes" }
   ]
  },
  { "title": "CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Total CPU Time",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{app=\"cloudserver-front\"}"
    }
   ]
  },
  {
   "title": "User CPU Time",
   "type": "graph",
   "description": "Total user CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "process_cpu_user_seconds_total{app=\"cloudserver-front\"}"
    }
   ]
  },
  {
   "title": "System CPU Time",
   "type": "graph",
   "description": "Total system CPU time spent in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "process_cpu_system_seconds_total{app=\"cloudserver-front\"}"
    }
   ]
  }
 ]
}