import { When, Then } from '@cucumber/cucumber';
import { strict as assert } from 'assert';
import Zenko from '../../world/Zenko';
import { CacheHelper, ClientOptions, VaultAuth } from 'cli-testing';
import { runActionAgainstBucket } from 'steps/utils/utils';

When('the user tries to perform {string} on the bucket', async function (this: Zenko, action: string) {
    await runActionAgainstBucket(this, action);
});

When('the user tries to perform vault auth {string}', async function (this: Zenko, action: string) {
    const lastIdentity = this.getSavedIdentity();
    const userCredentials = this.awsClients.getCredentials(lastIdentity.identityName);

    if (!this.parameters.VaultAuthHost) {
        throw new Error('Vault auth endpoint is not set. Make sure the `VaultAuthHost` world parameter is defined.');
    }

    const vaultAuthClientOptions: ClientOptions = {
        AccessKey: userCredentials.accessKeyId,
        SecretKey: userCredentials.secretAccessKey,
        SessionToken: userCredentials.sessionToken,
        ip: this.parameters.VaultAuthHost,
        ssl: CacheHelper.parameters ? CacheHelper.parameters.ssl as boolean : undefined,
    };

    switch (action) {
    case 'GetAccountInfo':
        try {
            this.saveS3Result(await VaultAuth.getAccounts([
                lastIdentity.accountName || this.parameters.AccountName,
            ], null, null, {
                // @ts-expect-error accountNames is not generated by CTST yet
                accountNames: true,
            }, vaultAuthClientOptions));
        } catch (err) {
            this.saveS3Error(err);
        }
        break;
    default:
        throw new Error(`Action ${action} is not supported`);
    }
});

Then('the user should be able to perform successfully the {string} action', function (this: Zenko, action: string) {
    const outcome = this.getS3Outcome();
    switch (action) {
    case 'MetadataSearch':
    case 'GetAccountInfo':
        assert.ok(outcome.ok, `Expected success but got: ${!outcome.ok ? outcome.error.message : ''}`);
        break;
    default:
        assert.ok(outcome.ok, `Expected success but got: ${!outcome.ok ? outcome.error.message : ''}`);
    }
});

Then('the user should not be able to perform the {string} action', function (this: Zenko, action: string) {
    const outcome = this.getS3Outcome();
    switch (action) {
    case 'GetAccountInfo': {
        const data = outcome.ok ? outcome.data as { code?: string } : null;
        assert.ok(
            (outcome.ok && data?.code === 'AccessDenied') ||
            (!outcome.ok && outcome.error.name === 'AccessDenied'),
        );
        break;
    }
    default:
        assert.ok(outcome.ok);
    }
});

Then('the user should receive {string} error', function (this: Zenko, error: string) {
    const outcome = this.getS3Outcome();
    assert.ok(
        !outcome.ok && (
            outcome.error.name?.includes(error) ||
            outcome.error.message?.includes(error)
        ),
        `Expected error "${error}" but got name: "${outcome.ok ? '' : outcome.error.name}", message: "${outcome.ok ? '' : outcome.error.message}"`,
    );
});
